### ISSUE TITLE
tools文件夹下的minimum_2stage_inference.py的使用方法

### ISSUE THREAD

**Issue by ouyang25** [WenmuZhou/PytorchOCR#101]
作者，您好！我对您们所做的这个代码一直都有在关注，现在我遇到的情况是，det_infer/det_train和rec_infer/rec_train都在自己的电脑上跑通了，但是minimum_2stage_inference.py这个没办法去跑通它，如何在这个代码中放入图片后，出检测框和文字识别的结果一直困扰着我，希望您可以给出2stage_inference的readme文件，非常感谢！希望能得到您的回复，谢谢！

**Comment by novioleo** [comment]
@ouyang25 那个代码我没写完。哈哈哈哈哈。没时间写。所以就太监了。

**Comment by novioleo** [comment]
@ouyang25 你可以提问，我可以解决。

**Comment by ouyang25** [comment]
我哭了，debug了很久，然后还是没跑通。跪求大佬抽出时间早日写完，follow大佬的日子挺幸福的，哈哈。

**Comment by novioleo** [comment]
这个时间不确定。好久没写了。代码都忘了。2333

**Comment by ouyang25** [comment]
非常相信大佬的能力，你只要有空出手来做，相信在较短时间内都可以完成。小菜鸟我非常期待您的更新！
