### ISSUE TITLE
检测模糊文字的思路

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#105]
大佬，看了你许多源代码，收益匪浅。
请教你一个问题，我有一个坑爹的task需要识别模糊字。
但学习模糊字的特征真的是太困难了，我有个相反的思路:
用大量高清的样本去训练模型，不让模型具备泛化能力，然后在推理阶段同样用高清图片识别文字内容(我的task可以具备这样的推理环境)，理论上模糊字会识别成奇怪的内容，这样可以通过比较识别结果和原本文的差异来判断是否有模糊字。
------------------------------------------------------------------------------------------------------------------
我的task因为从头到尾预测阶段只有一个样本(只是为了判断一张发票上有没有印模糊或者印错的字，不需要考虑泛化性和鲁棒性)， 您觉得这个方案可不可行。

**Comment by novioleo** [comment]
确实可以用你说的方案，不过建议还是做个简单的不确定性估计。这样比较简单。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;terrancraft&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月28日(星期三) 晚上6:38
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WenmuZhou/PytorchOCR] 检测模糊文字的思路 (#105)

**Comment by terrancraft** [comment]
> 确实可以用你说的方案，不过建议还是做个简单的不确定性估计。这样比较简单。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;terrancraft&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年10月28日(星期三) 晚上6:38 收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[WenmuZhou/PytorchOCR] 检测模糊文字的思路 (#105)

您指的是用dropout计算识别文字模型的不确定度吗？具体方案不太清楚，望指教。

**Comment by novioleo** [comment]
不确定性估计是一个技术名词。自己搜。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;terrancraft&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月30日(星期五) 下午5:46
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Tao Luo&quot;<744351893@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WenmuZhou/PytorchOCR] 检测模糊文字的思路 (#105)
