### ISSUE TITLE
文字识别方面的问题

### ISSUE THREAD

**Issue by yangfei963158659** [WenmuZhou/PytorchOCR#108]
楼主，你好。我用resnet18作为backbone训练crnn，训练过程很正常，infer的过程也政策。但是我用res50和res34作为backbone，loss一直降不下去，acc一直为0，是不是训练代码有bug呢?

**Comment by novioleo** [comment]
训练代码没有bug。你的这个问题，更多的可能是预训练的值的问题或者数据集的问题。麻烦check一下。另外查看下backbone是否是train的状态

**Comment by cendelian** [comment]
> 楼主，你好。我用resnet18作为backbone训练crnn，训练过程很正常，infer的过程也政策。但是我用res50和res34作为backbone，loss一直降不下去，acc一直为0，是不是训练代码有bug呢?



> 训练代码没有bug。你的这个问题，更多的可能是预训练的值的问题或者数据集的问题。麻烦check一下。另外查看下backbone是否是train的状态

大佬 项目文字识别部分支持的backbone只是resnet系列吗？支持mobilenet系列吗？

**Comment by WenmuZhou** [comment]
有mv3哈
