### ISSUE TITLE
新错误类型：Attribute error

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#113]
**您好，出现了新的错误：
模型虽然跑了起来，但是第一个saving point之后就出现了错误。
而且accuracy的值一直是0.**

![error2first](https://user-images.githubusercontent.com/51820927/98631614-25541780-2361-11eb-8a91-6252c25550da.jpg)
![error_log2](https://user-images.githubusercontent.com/51820927/98631618-27b67180-2361-11eb-84bc-5dd5dd219798.jpg)

**望解答！由衷感谢！**

**Comment by novioleo** [comment]
images是tensor不是字符串。check一下自己的数据是不是读取错误了。

**Comment by terrancraft** [comment]
我在查找

**Comment by terrancraft** [comment]
貌似是eval的数据没读出来
