### ISSUE TITLE
  padded_polygon = np.array(padding.Execute(distance)[0]) IndexError: list index out of range

### ISSUE THREAD

**Issue by dengfenglai321** [WenmuZhou/PytorchOCR#115]
以下代码报错
make_order_map.py

` padded_polygon = np.array(padding.Execute(distance)[0])`

**File "/data2/deliancen/workpace/OCR/PytorchOCR/torchocr/datasets/det_modules/make_border_map.py", line 54, in draw_border_map
    padded_polygon = np.array(padding.Execute(distance)[0])
IndexError: list index out of range**

**Comment by novioleo** [comment]
@cendelian 抱歉看到晚了。能麻烦print一下错误的时候distance的值么

**Comment by cendelian** [comment]
> @cendelian 抱歉看到晚了。能麻烦print一下错误的时候distance的值么
![image](https://user-images.githubusercontent.com/50360389/98936926-a4437e80-2520-11eb-99f2-e61d1dd85306.png)

对应的代码如下：
```
    # if padding.Execute(distance) is None:
        #     print('None')
        print('distance : ',distance)
        print('----------------------------')
        padded_polygon = np.array(padding.Execute(distance)[0])
        print('padded_polygon: ',padded_polygon)
        cv2.fillPoly(mask, [padded_polygon.astype(np.int32)], 1.0)
```

请问该怎么解决？
运行时batch ：1， numworker：1

**Comment by novioleo** [comment]
这个是你这个标注数据区域shrink的话太小，小于0了。你可以调整shrink比例，也可以check一下你的这个case的标注情况。

**Comment by cendelian** [comment]
> 这个是你这个标注数据区域shrink的话太小，小于0了。你可以调整shrink比例，也可以check一下你的这个case的标注情况。

shrink比例在哪里调？调小还是调大？
还有一样的数据集，我在大佬WenmuZhou / DBNet.pytorch这个项目里就能跑通没有任何错误。

我感觉WenmuZhou / DBNet.pytorch 和WenmuZhou / PytorchOCR这两个项目的文本检测部分都差不多吧

**Comment by cendelian** [comment]
> 这个是你这个标注数据区域shrink的话太小，小于0了。你可以调整shrink比例，也可以check一下你的这个case的标注情况。

我使用WenmuZhou / DBNet.pytorch跑一样的数据集，推理发现结果的标注的确比正常文本框要小。。。比如下图：
![image](https://user-images.githubusercontent.com/50360389/99021531-d645f680-259b-11eb-8f3e-0bf6c210a04e.png)


大佬该怎么调shrink呢？
实在config下调那个shrink_ratio吗？调大？
      # db 预处理，不需要修改
```
            'pre_processes': [{'type': 'IaaAugment', 'args': [{'type': 'Fliplr', 'args': {'p': 0.5}},
                                                              {'type': 'Affine', 'args': {'rotate': [-10, 10]}},
                                                              {'type': 'Resize', 'args': {'size': [0.5, 3]}}]},
                              {'type': 'EastRandomCropData', 'args': {'size': [640, 640], 'max_tries': 50, 'keep_ratio': True}},
                              {'type': 'MakeBorderMap', 'args': {'shrink_ratio': 0.4, 'thresh_min': 0.3, 'thresh_max': 0.7}},
                              {'type': 'MakeShrinkMap', 'args': {'shrink_ratio': 0.4, 'min_text_size': 8}}],
```

**Comment by WenmuZhou** [comment]
框小了，需要unclip_ratio调大

**Comment by cendelian** [comment]
> 框小了，需要unclip_ratio调大

大佬你好，我将unclip_ration调到2.0了 还是报一样的错误

**Comment by novioleo** [comment]
我觉得是标注的数据有点问题

**Comment by aiboys** [comment]
hi
请问你解决了吗？
我也有遇到这个问题, 目前发现是坐标有负数，以及polygon出现交叉两个问题会导致这个情况，但除了这两种情况会导致pycliiper根据distance生成得到的padde_polygon出现多个list的情况，还有其余的条件也会出现，想知道如果你是按照取padded_polygon[0]依旧会报错吗？

**Comment by aiboys** [comment]
> hi
> 请问你解决了吗？
> 我也有遇到这个问题, 目前发现是坐标有负数，以及polygon出现交叉两个问题会导致这个情况，但除了这两种情况会导致pycliiper根据distance生成得到的padde_polygon出现多个list的情况，还有其余的条件也会出现，想知道如果你是按照取padded_polygon[0]依旧会报错吗？

**Comment by aiboys** [comment]
> 以下代码报错 make_order_map.py
> 
> ` padded_polygon = np.array(padding.Execute(distance)[0])`
> 
> **File "/data2/deliancen/workpace/OCR/PytorchOCR/torchocr/datasets/det_modules/make_border_map.py", line 54, in draw_border_map padded_polygon = np.array(padding.Execute(distance)[0]) IndexError: list index out of range**

https://github.com/WenmuZhou/PytorchOCR/issues/115#issue-739871537
