### ISSUE TITLE
生成自己的数据集文件

### ISSUE THREAD

**Issue by cendelian** [WenmuZhou/PytorchOCR#116]
大佬，请问下怎么生成自己的训练数据集对应的字典文件

**Comment by novioleo** [comment]
set

**Comment by cendelian** [comment]
> set

set?

**Comment by novioleo** [comment]
对自己的字符取set。

**Comment by cendelian** [comment]
> 对自己的字符取set。

哦，就是用集合的方法取到字符，然后将取到的所有字符添加进alphabets的digit.txt里面吗？一个字符一行，我理解正确吗？
需要注意顺序之类的吗？

**Comment by novioleo** [comment]
是这样的。没有顺序哈~

**Comment by cendelian** [comment]
> 是这样的。没有顺序哈~

已解决，感谢大佬，如果没有set，有一些重复的会影响吗？
此外，我训练一开始loss就是nan，有什么办法解决？调小学习率？还是其它

**Comment by novioleo** [comment]
会影响。nan应该是label错误导致

**Comment by cendelian** [comment]
> 会影响。nan应该是label错误导致

我现在查看了cnn的输出，cnn的输出都是nan，，，，，还没到rnn+ctc。。。。cnn输出全是nan，大佬大概知道是什么原因吗？

**Comment by novioleo** [comment]
> > 会影响。nan应该是label错误导致
> 
> 我现在查看了cnn的输出，cnn的输出都是nan，，，，，还没到rnn+ctc。。。。cnn输出全是nan，大佬大概知道是什么原因吗？

这个不好确定，cnn中存在nan那么大概率你在归一化就错了。
