### ISSUE TITLE
同样训练准确率一直为0

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#118]
用了lmdb和textline两个格式的数据集训练出来的accuracy都为0. 崩溃了。
比如下图:
![image](https://user-images.githubusercontent.com/51820927/98917814-2e371b80-2510-11eb-9e7a-18b7a9586d65.png)

是不是linux环境下textline前面的img_path都要是绝对路径？
比如改成/home/user/Pytorch-master/imageset.*.png之类的？
望解答，谢谢！

**Comment by novioleo** [comment]
最好绝对路径哈~ @terrancraft

**Comment by novioleo** [comment]
acc为0，个人建议看看图片是否读取正确、label是否读取正确之类的基础问题

**Comment by terrancraft** [comment]
改成绝对路径之后 连loss都是0。。。。。。。。
label应该是读取正确的，因为eval的时候label内容显示在了黑屏中。。
可能是图片读取问题吧。但就是查不出来。。。。
此外我用的国外的os会不会受到影响。。。 比如出现什么编码类的坑爹问题。。

**Comment by cendelian** [comment]
> 改成绝对路径之后 连loss都是0。。。。。。。。
> label应该是读取正确的，因为eval的时候label内容显示在了黑屏中。。
> 可能是图片读取问题吧。但就是查不出来。。。。
> 此外我用的国外的os会不会受到影响。。。 比如出现什么编码类的坑爹问题。。

请问你解决这个问题了吗？ 我也遇到一样的问题

**Comment by novioleo** [comment]
> 改成绝对路径之后 连loss都是0。。。。。。。。
> label应该是读取正确的，因为eval的时候label内容显示在了黑屏中。。
> 可能是图片读取问题吧。但就是查不出来。。。。
> 此外我用的国外的os会不会受到影响。。。 比如出现什么编码类的坑爹问题。。

@terrancraft 你能把你输入到网络的tensor转换成numpy，print出来看下么

**Comment by terrancraft** [comment]
> > 改成绝对路径之后 连loss都是0。。。。。。。。
> > label应该是读取正确的，因为eval的时候label内容显示在了黑屏中。。
> > 可能是图片读取问题吧。但就是查不出来。。。。
> > 此外我用的国外的os会不会受到影响。。。 比如出现什么编码类的坑爹问题。。
> 
> @terrancraft 你能把你输入到网络的tensor转换成numpy，print出来看下么

不好意思，才看到这条信息。
**这个是train_loader里一个batch的数据，包括图片和标签。**
![show1](https://user-images.githubusercontent.com/51820927/101321221-611ec600-38a8-11eb-9d8f-74302dfe0ddb.jpg)
![show2](https://user-images.githubusercontent.com/51820927/101321237-6a0f9780-38a8-11eb-8316-72a4d1bb6365.jpg)
下面的是放进去net后的结果
![show3](https://user-images.githubusercontent.com/51820927/101321331-86133900-38a8-11eb-8252-2168e01c27b4.jpg)
我用的是icdar2015的数据

**Comment by terrancraft** [comment]
> > 改成绝对路径之后 连loss都是0。。。。。。。。
> > label应该是读取正确的，因为eval的时候label内容显示在了黑屏中。。
> > 可能是图片读取问题吧。但就是查不出来。。。。
> > 此外我用的国外的os会不会受到影响。。。 比如出现什么编码类的坑爹问题。。
> 
> 请问你解决这个问题了吗？ 我也遇到一样的问题

请参照上面一条信息

**Comment by terrancraft** [comment]
纠正 ： 从40个epoch开始的确有acc了 199epoch的时候如下，所以我的问题应该是解决了。

**Comment by terrancraft** [comment]
![image](https://user-images.githubusercontent.com/51820927/101429314-0471e880-3946-11eb-85a7-e08f3b83a050.png)
