### ISSUE TITLE
在ICDAR2015上训练CRNN，eval_acc很低

### ISSUE THREAD

**Issue by Aionrichman** [WenmuZhou/PytorchOCR#122]
![image](https://user-images.githubusercontent.com/28520971/100687101-a16ad980-33ba-11eb-82f1-ba2a112a2e97.png)
如图

**Comment by WenmuZhou** [comment]
纯ic15数据吗，那个数据量很少的

**Comment by Aionrichman** [comment]
嗯嗯，纯ic15数据。如果我需要训练英文模型的话，请问需要换一个什么数据集呢？

**Comment by Aionrichman** [comment]
> 纯ic15数据吗，那个数据量很少的

嗯嗯，纯ic15数据。所以这个训练结果没问题，增加数据就可以提升对吗？

**Comment by WenmuZhou** [comment]
对的

**Comment by Aionrichman** [comment]
> 对的

还想请教一下，https://github.com/WenmuZhou/OCR_DataSet里面的英文识别大礼包的字典文件在哪里可以下载啊

**Comment by WenmuZhou** [comment]
里面的百度云吧，或者去那个repo里找一下

**Comment by Aionrichman** [comment]
谢谢，使用大数据集训练果然OK了
