### ISSUE TITLE
icdar2015训练DB，precision 0.92 recall 0.63

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#123]
召回率有点偏低，请问是不是跟数据集过少有关。
不懂就问   有什么提升召回率的思路？
![image](https://user-images.githubusercontent.com/51820927/101127970-02581300-3642-11eb-84bd-c09eae5b8388.png)

**Comment by novioleo** [comment]
堆数据

**Comment by terrancraft** [comment]
优化模型呢？

**Comment by novioleo** [comment]
这个模型没有优化的必要了

**Comment by jeremy520-source** [comment]
> 召回率有点偏低，请问是不是跟数据集过少有关。
> 不懂就问 有什么提升召回率的思路？
> ![image](https://user-images.githubusercontent.com/51820927/101127970-02581300-3642-11eb-84bd-c09eae5b8388.png)

您好，我也是训练检测模型，但是报错，您遇到过吗？可否告知我解决的办法


![Uploading QQ图片20210311153552.png…]()

**Comment by YY007H** [comment]
你训练了多少轮呢？我从0训练到30轮，best metric, hmean: 0.40245947456679704, precision: 0.47904191616766467, recall: 0.346987951807228，好低
