### ISSUE TITLE
关于crnn转mnn的一些bug

### ISSUE THREAD

**Issue by cendelian** [WenmuZhou/PytorchOCR#125]
大佬你好
请问你尝试将crnn转过mnn吗？
目前发现crnn转mnn有一些问题，主要是在lstm部分，貌似lstm转mnn是不对的。。。导致mnn模型输出有错

**Comment by novioleo** [comment]
具体一点。
另外不建议转mnn。

**Comment by cendelian** [comment]
> 具体一点。
> 另外不建议转mnn。

你好，我文字识别crnn模型里面有lstm部分，转onnx没问题，onnx转mnn的时候出现如下：

[06:42:53] :31: ONNX Model ir version: 6
[06:42:53] :155: Check it out ==> 726 has empty input, the index is 4
[06:42:53] :155: Check it out ==> 777 has empty input, the index is 4
Start to Optimize the MNN Net...
[06:42:54] :64: Inputs: input
[06:42:54] :69: Outputs: output

mnn模型输出结果是不对的。
onnx模型输出维度是（1，x，2671），x是不固定的，
但是mnn模型输出固定式（2，1，96）

请问mnn支持lstm转换吗？怎么解决？

onnx中的lstm部分结构图如下：
![image](https://user-images.githubusercontent.com/50360389/101023836-47cb0080-35ae-11eb-9704-786127b4ee0c.png)

**Comment by cendelian** [comment]
> 具体一点。
> 另外不建议转mnn。

我们走的都是onnx -> mnn这条路，所以 。。。。必须要转mnn。。。。。。。。。。。。。。。。。。

**Comment by cendelian** [comment]
![image](https://user-images.githubusercontent.com/50360389/101452161-43189a80-3968-11eb-9239-babeb6126ff4.png)

**Comment by novioleo** [comment]
@cendelian 你是用什么工具转的？

**Comment by cendelian** [comment]
> @cendelian 你是用什么工具转的？

我先转成onnx，onnx推理是OK的，与pytorch一致。
然后用mnn转换工具将onnx转成mnn，mnn转换指令如下：
`mnnconvert -f ONNX --modelFile xxx.onnx --MNNModel xxx.mnn`

转换会出现
```
[06:42:53] :155: Check it out ==> 726 has empty input, the index is 4
[06:42:53] :155: Check it out ==> 777 has empty input, the index is 4
```

貌似lstm转换不对还是不支持啥的？？
并且转换后的mnn模型输出形状固定是（2， 1， 96）。。。。。。
正确的输出形状应该是（1，x, 字符数长度）。。

大佬麻烦帮忙看下哈，这个几天了。。。没搞定。。

**Comment by novioleo** [comment]
@cendelian https://convertmodel.com/ 先试试这个

**Comment by cendelian** [comment]
> @cendelian https://convertmodel.com/ 先试试这个

这个网址联转mnn都转不成功了。。报错如下：
![image](https://user-images.githubusercontent.com/50360389/101481967-e9789600-3990-11eb-8bcd-4df67b90d7ca.png)

**Comment by novioleo** [comment]
@cendelian 
你把模型分别导出为多个部分，例如backbone 、neck、head多个部分。每个onnx你进行转换下。这样问题也好排查

**Comment by cendelian** [comment]
> @cendelian
> 你把模型分别导出为多个部分，例如backbone 、neck、head多个部分。每个onnx你进行转换下。这样问题也好排查

怎么导出。。。

**Comment by novioleo** [comment]
每个module export到onnx啊。backbone、neck、head都是一个network module嘛。

**Comment by cendelian** [comment]
> 每个module export到onnx啊。backbone、neck、head都是一个network module嘛。

要加载权重参数后才能导出吧，可是加载后就是一个整体了，，怎么划分开导出

**Comment by novioleo** [comment]
你先加载参数嘛，加载完了之后这个net里面有多个module，`torch.onnx.export(net.backbone)`  这个样子的方式导出其中的某个module
@cendelian

**Comment by novioleo** [comment]
@cendelian 如何了？

**Comment by cendelian** [comment]
> @cendelian 如何了？

没解决。。。。。。

**Comment by novioleo** [comment]
> > @cendelian 如何了？
> 
> 没解决。。。。。。

@cendelian 
是没去弄还是遇到问题了？

**Comment by cendelian** [comment]
已经解决， 发现onnx转mnn有empty提示， 但是不影响MNN的推理结果。。。。。。。。。。。。。。。。。。。。。
所以这个提示可以忽略不计

**Comment by eldrick-dai** [comment]
@cendelian 你好请教一下，模型转onnx的时候输入输出的尺寸是动态的，这些是怎么处理的呢？谢谢

**Comment by nissansz** [comment]
> > 具体一点。
> > 另外不建议转mnn。
> 
> 你好，我文字识别crnn模型里面有lstm部分，转onnx没问题，onnx转mnn的时候出现如下：
> 
> [06:42:53] :31: ONNX Model ir version: 6 [06:42:53] :155: Check it out ==> 726 has empty input, the index is 4 [06:42:53] :155: Check it out ==> 777 has empty input, the index is 4 Start to Optimize the MNN Net... [06:42:54] :64: Inputs: input [06:42:54] :69: Outputs: output
> 
> mnn模型输出结果是不对的。 onnx模型输出维度是（1，x，2671），x是不固定的， 但是mnn模型输出固定式（2，1，96）
> 
> 请问mnn支持lstm转换吗？怎么解决？
> 
> onnx中的lstm部分结构图如下： ![image](https://user-images.githubusercontent.com/50360389/101023836-47cb0080-35ae-11eb-9704-786127b4ee0c.png)

你好，可以发一下pth转onnx的代码吗？
