### ISSUE TITLE
关于CTCLabelConverter的疑问

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#126]
decode结构中加了如下的判断条件会不会使拥有相同字母的单词无法被打印出来(比如'Hello'中的'l')
难道CTC算法默认每个字符中存在blank?
不太了解，望解答。
![image](https://user-images.githubusercontent.com/51820927/101434590-2ec7a400-394e-11eb-8c82-2008b898d073.png)

**Comment by novioleo** [comment]
不会的。decode出来一般是hhhhell(blank)ll(blank)ooooo
结果就是hello

**Comment by terrancraft** [comment]
get~
