### ISSUE TITLE
训练出来的CRNN 推理时没结果

### ISSUE THREAD

**Issue by terrancraft** [WenmuZhou/PytorchOCR#128]
详细请见图 
![image](https://user-images.githubusercontent.com/51820927/101454325-22564200-3974-11eb-925c-328f9a58075b.png)
预测结果和概率值都为空，感觉是model没有读出来？

**Comment by WenmuZhou** [comment]
那说明没有识别到啊

**Comment by novioleo** [comment]
同上

**Comment by terrancraft** [comment]
多张图片都没识别到。。奇怪

**Comment by novioleo** [comment]
@terrancraft 用训练集的图片试试

**Comment by terrancraft** [comment]
> @terrancraft 用训练集的图片试试
一样的
![image](https://user-images.githubusercontent.com/51820927/101881825-516ced80-3bd8-11eb-955b-e347e806a12d.png)
要不我发权重文件来，您看一看咋回事？

**Comment by zengchan** [comment]
我也是这样的，感觉代码是不是哪儿有问题

**Comment by corleonechensiyu** [comment]
出现这个结果的最主要原因是，你的label类别数目错了

**Comment by novioleo** [comment]
> 出现这个结果的最主要原因是，你的label类别数目错了

你说的对

**Comment by terrancraft** [comment]
类别数目不应该是classes + 1 吗? 哪里设定错了吗？

**Comment by corleonechensiyu** [comment]
> 类别数目不应该是classes + 1 吗? 哪里设定错了吗？

你仔细检查下，你这个结果就是类别数目不对，因为我测试过，检查下你的label.txt文件

**Comment by terrancraft** [comment]
我去检查一下

**Comment by terrancraft** [comment]
> 出现这个结果的最主要原因是，你的label类别数目错了

我没太懂。您的意思是一开始训练时用的label文件用set函数得到的字符个数和字典文件中的字符个数不相同？

**Comment by abner2015** [comment]
遇到类似问题，这和label没有关系吧，index都是0，label第一个index就是blank,所以就是空

**Comment by abner2015** [comment]
http://pan.baidu.com/s/1hqGbyQS
