### ISSUE TITLE
训练出来的没有结果可能是数据集太少或者训练次数不够，或者标签有问题多检查一下

### ISSUE THREAD

**Issue by zengchan** [WenmuZhou/PytorchOCR#130]
如上

**Comment by light1003** [comment]
检查训练集

**Comment by terrancraft** [comment]
问个细节问题，不包含空格的字典文件个数加上1是不是等于fc层的节点数？

**Comment by novioleo** [comment]
> 问个细节问题，不包含空格的字典文件个数加上1是不是等于fc层的节点数？

fc层的channels数

**Comment by terrancraft** [comment]
这个我知道。我想知道空格需不需要单独计算？

Tao Luo <notifications@github.com> 于2021年1月12日周二 下午3:21写道：

**Comment by novioleo** [comment]
空格是一个字符，跟其他字符一样------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Hu&amp;nbsp;Bo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月12日(星期二) 晚上7:03
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Tao Luo&quot;<744351893@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WenmuZhou/PytorchOCR] 训练出来的没有结果可能是数据集太少或者训练次数不够，或者标签有问题多检查一下 (#130)

**Comment by Tomhardy13** [comment]
我训练的精度一直是0，请问一般要多少数据，多少个epoch?我用了9000张数据，200个epoch
