### ISSUE TITLE
icdar2015识别训练的验证集的准确率仅为40%

### ISSUE THREAD

**Issue by w603080253** [WenmuZhou/PytorchOCR#133]
仅用您提供的文字识别算法，lr为0.0001，epoch为200，其他都没改，但识别准确率为0.41，请问哪里出现问题

**Comment by novioleo** [comment]
数据不够

**Comment by jeremy520-source** [comment]
> 仅用您提供的文字识别算法，lr为0.0001，epoch为200，其他都没改，但识别准确率为0.41，请问哪里出现问题

您好。我用这个数据进行检测的训练，报错，可否告知我怎么改让它跑起来呢

![QQ图片20210311153552](https://user-images.githubusercontent.com/62582352/110752970-e4bdc980-8280-11eb-9de8-36b044a6addb.png)
