### ISSUE TITLE
内存泄漏，有没有大佬遇到过这个问题，求解答。

### ISSUE THREAD

**Issue by zengchan** [WenmuZhou/PytorchOCR#135]

**Comment by WenmuZhou** [comment]
详细描述一下具体的环境，代码和复现步骤

**Comment by zengchan** [comment]
V100,单卡运行，batchsize32,num_workers8,查看到的cpu内存占用一直上升，16Ggpu显存占用率只有百分之50-60，没一会儿就cuda out of memory。按照readme里面UDA_VISIBLE_DEVICES=0 python3 tools/rec_infer.py运行的。

**Comment by novioleo** [comment]
num_workers=-1试试。

**Comment by novioleo** [comment]
@ZenFSheng 请问解决没有，可以关了吗？

**Comment by TonXX** [comment]
你说的这个num_workers=-1，不是只有训练时候才会用到吗。正常det_infer和rec_infer也用吗？我遇到题主相同的问题了。

**Comment by TonXX** [comment]
> num_workers=-1试试。
你说的这个num_workers=-1，不是只有训练时候才会用到吗。正常det_infer和rec_infer也用吗？我遇到题主相同的问题了

**Comment by novioleo** [comment]
如果是infer的话，可以参考专用的部署代码：
https://github.com/novioleo/Savior

https://github.com/novioleo/Savior/blob/master/Operators/ExampleTextDetectOperator/TextDetectOperator.py
https://github.com/novioleo/Savior/blob/master/Operators/ExampleTextRecognizeOperator/TextRecognizeOperator.py

@TonXX

**Comment by light1003** [comment]
> V100,单卡运行，batchsize32,num_workers8,查看到的cpu内存占用一直上升，16Ggpu显存占用率只有百分之50-60，没一会儿就cuda out of memory。按照readme里面UDA_VISIBLE_DEVICES=0 python3 tools/rec_infer.py运行的。

可以检查下你的测试样本里是不是有超级长的

**Comment by morestart** [comment]
batchsize 16以下没事 32以上会有oom的问题
