### ISSUE TITLE
识别训练遇到问题，望解答

### ISSUE THREAD

**Issue by longxiang946** [WenmuZhou/PytorchOCR#140]
RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)

**Comment by novioleo** [comment]
你check一下ctc_loss_gpu的device是不是cuda，不是的话，代码里面to一下。

**Comment by longxiang946** [comment]
能否说的详细点，原代码未改动过，在哪里添加.to("cuda")

**Comment by longxiang946** [comment]
不用回答了，我已经知道了
