### ISSUE TITLE
如何训练如此小的网络？

### ISSUE THREAD

**Issue by longxiang946** [WenmuZhou/PytorchOCR#146]

**Comment by novioleo** [comment]
@longxiang946 训练分为多阶段，最开始我们训练的话都是会用res50等大网络进行的训练。主要还是用尽可能多的数据和增广完成相应的操作。当然也包括的lrs、loss的调整。当在大模型上收敛之后我们就会尝试distill到小模型上面。减小大小模型的KL即可。然后将得到的小模型再进行finetune。
crnn的模型最小可以到几百K。举个简单的例子，目前4.2M，量化之后是1M左右，然后在进行pruning channel可以到800K左右。然后再进行element wise的pruning再进行sparsity，然后能到600+K。当然精度是会对应的降低的。

另外一个点就是减少降低lstm的隐层的大小以及timestep的长度。甚至于可以干掉lstm，直接将最后的cnn进行reshape之后直接回归。只是说这样的模型没有什么语义性，适合于诸如验证码等场景。

**Comment by longxiang946** [comment]
我想复现4.2M模型的训练过程，想知道你们是训练出来的，修改了哪些地方

**Comment by novioleo** [comment]
@longxiang946 我在上面提过，你可以修改lstm的隐层的大小。timestep的长度。甚至于把lstm干掉直接用cnn。都是可以的。
我们的模型也就是隐层少，timestep小。

**Comment by novioleo** [comment]
具体模型参数你可以将我们的模型load进去，然后利用`torchsummary`查看对应网络结构。
