### ISSUE TITLE
您好，我用的icdar2015数据集来做检测的训练，可是报错，一直解决不了，可以帮忙看看嘛？

### ISSUE THREAD

**Issue by jeremy520-source** [WenmuZhou/PytorchOCR#147]
- [ ] #107 
 @![QQ图片20210311153552](https://user-images.githubusercontent.com/62582352/110752227-f0f55700-827f-11eb-92f7-14b70da8db63.png)

**Comment by jeremy520-source** [comment]
@novioleo  谢谢您，实在不知道是为什么报错，转格式也尝试了，都未解决。

**Comment by novioleo** [comment]
@jeremy520-source 改下代码
```python
data_dict[k] = torch.stack(torch.from_numpy(data_dict[k]),0)
```

**Comment by jeremy520-source** [comment]
您好，我改了代码，然后又运行，可还是报错。你可以再帮我看看么。谢谢您
![QQ图片20210311155144](https://user-images.githubusercontent.com/62582352/110753696-d7eda580-8281-11eb-8be0-115732b2be26.png)
@novioleo

**Comment by novioleo** [comment]
自己根据报错信息，进行debug，然后修改即可。

**Comment by apple2333cream** [comment]
我也碰到过，改成这样就好了
 
            try: # text_ploys
                data_dict[k]=[torch.from_numpy(x) for  x in data_dict[k]] # [numoy,numoy……]->[tensor,tensor……]
            except: #imgs
                pass
            data_dict[k] = torch.stack(data_dict[k], 0)
