### ISSUE TITLE
The size of tensor a (64) must match the size of tensor b (63) at non-singleton dimension 3

### ISSUE THREAD

**Issue by fanbooo** [WenmuZhou/PytorchOCR#149]
Hi作者，我在执行到dec_train.py中train下的eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)时，
出现了报错The size of tensor a (64) must match the size of tensor b (63) at non-singleton dimension 3；

断点执行时发现是eval_loader loader数据加载时图片不是1:1形式，请问这个在config文件中怎么对test部分作修改呢？
![image](https://user-images.githubusercontent.com/27717525/111161178-cd127800-85d5-11eb-8e44-a1ae4bf74878.png)

**Comment by Dennis-YB** [comment]
config里eval加个:{'type': 'EastRandomCropData', 'args': {'size': [960, 960], 'max_tries': 50, 'keep_ratio': True}}]

**Comment by novioleo** [comment]
图像尺寸不对。是32的倍数。麻烦check下。

**Comment by Dennis-YB** [comment]
> 图像尺寸不对。是32的倍数。麻烦check下。
请问输入怎么更改，数据集里的图像尺寸都不同，需要在代码那个位置改呢

**Comment by Dennis-YB** [comment]
> 图像尺寸不对。是32的倍数。麻烦check下。

请问输入怎么更改，数据集里的图像尺寸都不同，需要在代码那个位置改呢

**Comment by novioleo** [comment]
你改下dataset里面关于边长是32倍的预处理。那个地方有错。最终效果就是输入图像和label的边长都是32的倍数即可。

**Comment by Dennis-YB** [comment]
> 你改下dataset里面关于边长是32倍的预处理。那个地方有错。最终效果就是输入图像和label的边长都是32的倍数即可。

![image](https://user-images.githubusercontent.com/33629530/114641756-43091c80-9d05-11eb-90af-0c419e16619f.png)
请问我这样修改可以吗？

**Comment by novioleo** [comment]
@Bourne-M

**Comment by Bourne-M** [comment]
把你加的 eastrandomcropdata 去掉，拉取最新的代码
