### ISSUE TITLE
DB_fpn层的问题

### ISSUE THREAD

**Issue by fanbooo** [WenmuZhou/PytorchOCR#155]
Hi作者:
    在det_train的eval里,当图片为非1:1的时候,就会报下列错误,请问这个在config里怎么改eval的配置?

The size of tensor a (68) must match the size of tensor b (67) at non-singleton dimension 2
![image](https://user-images.githubusercontent.com/27717525/112595666-b249ca00-8e45-11eb-92e4-02d8b7cee373.png)

image的size
![image](https://user-images.githubusercontent.com/27717525/112595744-c988b780-8e45-11eb-89c1-374892b1a486.png)

**Comment by novioleo** [comment]
图像尺寸错误。不是32的倍数，麻烦自己resize下。

**Comment by fanbooo** [comment]
> 图像尺寸错误。不是32的倍数，麻烦自己resize下。

谢谢,config文件中是不是有勘误?
1.  'pre_processes': [{'type': 'ResizeFShortSize', 'args': {'short_size': 736, 'resize_text_polys': False}}],应改成'pre_processes': [{'type': 'ResizeFixedSize', 'args': {'short_size': 736, 'resize_text_polys': True}}]
2. ResizeFixedSize中改成
    if self.resize_text_polys:
            text_polys[:, :, 0] =  (text_polys[:, :, 0] * ratio_w)
            text_polys[:, :, 1] =  (text_polys[:, :, 1] *ratio_h)

**Comment by novioleo** [comment]
@fanbooo 确实可能有问题。您调通之后，可以麻烦PR一个么？
