### ISSUE TITLE
有关cfg.datasets.alphablet的问题

### ISSUE THREAD

**Issue by wzl639** [WenmuZhou/PytorchOCR#157]
![image](https://user-images.githubusercontent.com/74966578/112924171-3b147e80-9142-11eb-8ff4-10f3099cde94.png)
这里是吧cfg.datasets.alphablet变成了字典中的字符串对吧，我直接运行rec_train.py 报错
![image](https://user-images.githubusercontent.com/74966578/112924315-7a42cf80-9142-11eb-838a-69b9ee7d11d9.png)
错误是应为 调用label_convert.py 模块时将cfg.datasets.alphablet作为一个txt文件打开，但是在rec_train.py 中已经将cfg.datasets.alphablet变为了字母表
![image](https://user-images.githubusercontent.com/74966578/112924361-8cbd0900-9142-11eb-9051-0be241f05120.png)
请问这个是什么情况

**Comment by wzl639** [comment]
望大佬解答

**Comment by novioleo** [comment]
你先改下代码，后面我们会集中修复。你既然都知道是字母表了，最终也只是在dict_character中，略微改下代码吧。

**Comment by wzl639** [comment]
> 你先改下代码，后面我们会集中修复。你既然都知道是字母表了，最终也只是在dict_character中，略微改下代码吧。

好的 谢谢作者大大
