### ISSUE TITLE
有关CRNN模型n_class的问题

### ISSUE THREAD

**Issue by wzl639** [WenmuZhou/PytorchOCR#159]
作者你好，我用你提供的模型infer结果很好，看了模型的配置文件n_class==6625， 字典为ppocr_keys_v1.txt，但是字典中字符貌似字符个数为6623个，n_class不应该是字符个数+1吗 那我如果也用ppocr_keys_v1.txt作为字典，那模型配置n_class该设置为多少呢，之前训练我设置n_class=6624, 训练有点问题，想问下是这个原因吗

**Comment by novioleo** [comment]
还有空格。所以是6625

**Comment by wzl639** [comment]
> 还有空格。所以是6625

好的谢谢作者

**Comment by wzl639** [comment]
> 还有空格。所以是6625

我想问下 你们提供CRNN，具体是用啥数据集跑的多久，我现在训练的准确率一直在0.9 左右
