### ISSUE TITLE
检测代码训练自己的数据集结果都是0

### ISSUE THREAD

**Issue by Dennis-YB** [WenmuZhou/PytorchOCR#165]
![image](https://user-images.githubusercontent.com/33629530/114508393-e0f9da00-9c66-11eb-8080-c012f0067847.png)
用自己的数据集训练检测代码结果都是0，为什么呢？因为数据量少吗，预训练模型我也没用。

**Comment by novioleo** [comment]
最近在fix这个问题，似乎是后处理代码没弄对。届时问题解决了，我会在issue中回复你。给你造成麻烦了~

**Comment by Dennis-YB** [comment]
> 最近在fix这个问题，似乎是后处理代码没弄对。届时问题解决了，我会在issue中回复你。给你造成麻烦了~

好的谢谢，期待您的fix。

**Comment by binwang672012** [comment]
同样遇到这个问题

**Comment by novioleo** [comment]
拉取最新代码试试。修复了后处理。 @Dennis-YB @binwang672012

**Comment by hhhhhhogan** [comment]
同样遇到这个问题，已拉去最新的代码(master分支)，torch版本为 1.8.1+cu111，opencv版本为3.4.11.41.，4.2.0.34也试过。一样为零？请问是什么原因呢？@novioleo      @Dennis-YB @binwang672012

**Comment by junjieliwhu** [comment]
我也遇到这个问题
