### ISSUE TITLE
预训练模型数据集

### ISSUE THREAD

**Issue by wzl639** [WenmuZhou/PytorchOCR#168]
作者你好 我想问下你们提供的识别模型是用什么数据集训练的

**Comment by novioleo** [comment]
很多

**Comment by wzl639** [comment]
> 


> 很多

能不能具体说说 我想自己从头训练一遍

**Comment by wzl639** [comment]
> > 
> 
> > 很多
> 
> 能不能具体说说 我想自己从头训练一遍

是你们给的所有识别数据集吗，  那我想再问下 要达到你们的效果 大概需要多少数据量，训练多久 我自己尝试过360万那个 但是鲁棒性没你们的好

**Comment by novioleo** [comment]
我们的模型是转的paddle的。我们以前自己训练过，差不多上千万的数据吧。但是也没有paddle的好，后来就放弃了。数据集的话，以前分享了，但是百度云给封了。
