### ISSUE TITLE
识别效果不好

### ISSUE THREAD

**Issue by liuwenfu1218** [WenmuZhou/PytorchOCR#169]
icdar2015运行db，准确率89，recall 40 识别不出来框，请问一下是什么原因

**Comment by novioleo** [comment]
可能是后处理的问题。最近准备fix这个。

**Comment by Bourne-M** [comment]
> icdar2015运行db，准确率89，recall 40 识别不出来框，请问一下是什么原因

暂时的处理办法是 回滚下 DBPostProcess.py文件到上一个版本

**Comment by liuwenfu1218** [comment]
> 可能是后处理的问题。最近准备fix这个。

好的了解，感谢大佬回复。

**Comment by liuwenfu1218** [comment]
> > icdar2015运行db，准确率89，recall 40 识别不出来框，请问一下是什么原因
> 
> 暂时的处理办法是 回滚下 DBPostProcess.py文件到上一个版本

好的感谢大佬解答。

**Comment by novioleo** [comment]
重新拉取一下，重新训练试试 @liuwenfu1218

**Comment by Bourne-M** [comment]
> > icdar2015运行db，准确率89，recall 40 识别不出来框，请问一下是什么原因
> 
> 暂时的处理办法是 回滚下 DBPostProcess.py文件到上一个版本

算了，别回滚了，已经fix了，重新拉取新代码吧。不过你这训练的也太惨了。。。。

**Comment by liuwenfu1218** [comment]
> 重新拉取一下，重新训练试试 @liuwenfu1218

好的 谢谢

**Comment by liuwenfu1218** [comment]
> > > icdar2015运行db，准确率89，recall 40 识别不出来框，请问一下是什么原因
> > 
> > 
> > 暂时的处理办法是 回滚下 DBPostProcess.py文件到上一个版本
> 
> 算了，别回滚了，已经fix了，重新拉取新代码吧。不过你这训练的也太惨了。。。。

嘿嘿，我再多试试，训练的不够。

**Comment by DimplesL** [comment]
![image](https://user-images.githubusercontent.com/22879053/115984993-51e0b080-a5dc-11eb-9de7-5893cc0b3e65.png)
个人感觉这部分list append的过程有问题，仅看了代码，没有测试
@Bourne-M

**Comment by novioleo** [comment]
@DimplesL 你说的对，不仅有错，还有单词拼写错误

**Comment by DimplesL** [comment]
> @DimplesL 你说的对，不仅有错，还有单词拼写错误

嗯。。还有拼写错误。。

**Comment by novioleo** [comment]
@DimplesL 感谢提出。以后我们会仔细点检查一下。。。抱歉。

**Comment by YY007H** [comment]
你训练了多少轮呢？我从0训练到30轮，best metric, hmean: 0.40245947456679704, precision: 0.47904191616766467, recall: 0.346987951807228，好低

**Comment by Bourne-M** [comment]
> 你训练了多少轮呢？我从0训练到30轮，best metric, hmean: 0.40245947456679704, precision: 0.47904191616766467, recall: 0.346987951807228，好低

多少数据，backbone是啥

**Comment by YY007H** [comment]
@Bourne-M 就是icdar2015的数据集，backbone用的mobilenet_v3

**Comment by Bourne-M** [comment]
> @Bourne-M 就是icdar2015的数据集，backbone用的mobilenet_v3

再跑一个晚上 神奇的事情就发生了

**Comment by YY007H** [comment]
@Bourne-M 😂，要跑这么久么，loss一直徘徊在2.5左右，有点懵，不知道他们怎么跑的那么高的

**Comment by Bourne-M** [comment]
> @Bourne-M 😂，要跑这么久么，loss一直徘徊在2.5左右，有点懵，不知道他们怎么跑的那么高的

接着跑吧

**Comment by liuwenfu1218** [comment]
> @DimplesL 你说的对，不仅有错，还有单词拼写错误

大佬这段post process代码是不是不能用

**Comment by novioleo** [comment]
> > @DimplesL 你说的对，不仅有错，还有单词拼写错误
> 
> 大佬这段post process代码是不是不能用

应该你简单改下就可以用了
