### ISSUE TITLE
大神，什么时候开源竖排文字识别呀

### ISSUE THREAD

**Issue by CYHYCY** [WenmuZhou/PytorchOCR#172]

**Comment by Bourne-M** [comment]
现在的模型就可以了啊，把你的文字图像逆时针转90°

**Comment by CYHYCY** [comment]
@Bourne-M 感谢大神的解答，刚找了一张图片试了一下，果然很强
<img width="1093" alt="34" src="https://user-images.githubusercontent.com/39784724/118099421-c81c4a00-b407-11eb-951a-f5ed5e38afce.png">
