### ISSUE TITLE
关于训练数据的问题

### ISSUE THREAD

**Issue by fantasyfulan** [WenmuZhou/PytorchOCR#173]
我用python3 tools/det_train.py训练自己的数据，报错：file tools/det_train.py line 157 in evaluate: is_output_polygon=metric.is_output_polygon 
typeerror:__call__() got an unexpected keyword argument 'is_output_polygon'，但是我查看并测试metric.is_output_polygon 是没有问题的，可能是line 157 post_precess函数的问题，但是不知道问题出在哪里，望指点

**Comment by novioleo** [comment]
代码忘记传进去。你自己改下。我回头改下

**Comment by fantasyfulan** [comment]
麻烦你上传一下。谢谢了

**Comment by fantasyfulan** [comment]
我改了以后发现，还是缺东西，一些函数没定义，可以的话，麻烦上传一下。
