### ISSUE TITLE
训练时前向传播出现nan

### ISSUE THREAD

**Issue by tangmiao0** [WenmuZhou/PytorchOCR#174]
改batch_size时，前向传播时输出全为nan，在计算loss报错
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Loss.cu:106: block: [10,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.

**Comment by novioleo** [comment]
@Bourne-M 你上次怎么解决的？~

**Comment by tangmiao0** [comment]
@novioleo necks的网络为FPN，输出为256通道没问题，输出通道为96会出现这样的情况。可能是ConvBnRelu的，可以改成Relu6实验一下。

**Comment by novioleo** [comment]
@tangmiao0 辛苦大佬了。你测完之后希望给我们一个反馈或者pr帮助我们改进项目。
