### ISSUE TITLE
对于一些少见的文字识别效果不好

### ISSUE THREAD

**Issue by MgArcher** [WenmuZhou/PytorchOCR#180]
发现您模型有些问题，针对一些不常用的字很容易出错
![5537dec4a08fe26e241091d318f441a](https://user-images.githubusercontent.com/37403293/119330029-620dad80-bcb8-11eb-86e6-9f1e5fbf36c2.png)
![5ac5417e87d5d3fdd6abc6849465f9e](https://user-images.githubusercontent.com/37403293/119330300-a6994900-bcb8-11eb-8a8d-45d1bf9843b7.png)
![e410a44d4d8e7a0c9fdf83ed3d9ea67](https://user-images.githubusercontent.com/37403293/119330310-a7ca7600-bcb8-11eb-96a2-d8e867c116ed.png)
其中 闫字识别成问，邝字识别成郑等等

**Comment by novioleo** [comment]
@MgArcher 这个是必然的~这个是百度发布的模型，他们也是主要考虑的是常用字~如果您那有需要，可以考虑针对于您的数据情况进行单独训练

**Comment by MgArcher** [comment]
好的，感谢大佬！顺便想问问您这个百度发布的模型是在哪里找的呢，能否给个链接

**Comment by novioleo** [comment]
@MgArcher 就paddleocr

**Comment by MgArcher** [comment]
感谢！
