### ISSUE TITLE
OCR识别出来内容不返回出来？

### ISSUE THREAD

**Issue by huwei1024** [WenmuZhou/PytorchOCR#181]
OCR识别出来内容不返回出来？

**Comment by novioleo** [comment]
请您认真阅读代码~感谢您的支持。

**Comment by huwei1024** [comment]
@novioleo 
只是打到图片上了，没返回文字呀？

`
def do_predict(self, img):        box_list, score_list = self.det_model.predict(img)        if len(box_list) == 0:            return [], [], img        draw_box_list = [tuple(map(tuple, box)) for box in box_list]        imgs =[get_rotate_crop_image(img, box) for box in box_list]        texts = self.rec_model.predict(imgs)        texts = [txt[0][0] for txt in texts]        debug_img = draw_ocr_box_txt(img, draw_box_list, texts)        return box_list, score_list, debug_img

`

**Comment by yufanxin** [comment]
同问，好像并没有看到返回识别结果的code

**Comment by yufanxin** [comment]
> 
> 
> OCR识别出来内容不返回出来？

请问一下你使用ocr_infer的检测和识别效果怎么样，我这里分别训练db检测和ocr召回率和精度都还可以，但是用ocr_infer检测+识别时效果很差

**Comment by novioleo** [comment]
> @novioleo
> 只是打到图片上了，没返回文字呀？
> 
> `
> def do_predict(self, img): box_list, score_list = self.det_model.predict(img) if len(box_list) == 0: return [], [], img draw_box_list = [tuple(map(tuple, box)) for box in box_list] imgs =[get_rotate_crop_image(img, box) for box in box_list] texts = self.rec_model.predict(imgs) texts = [txt[0][0] for txt in texts] debug_img = draw_ocr_box_txt(img, draw_box_list, texts) return box_list, score_list, debug_img
> 
> `

@huwei1024 那你在那个地方return一下。应该难度不大吧？

**Comment by novioleo** [comment]
> > OCR识别出来内容不返回出来？
> 
> 请问一下你使用ocr_infer的检测和识别效果怎么样，我这里分别训练db检测和ocr召回率和精度都还可以，但是用ocr_infer检测+识别时效果很差

麻烦是定位的问题还是后处理的问题还是识别的问题。细化点。
