### ISSUE TITLE
首页提供的模型效果较差

### ISSUE THREAD

**Issue by Dajiang1202** [WenmuZhou/PytorchOCR#183]
模型：使用 ch_det_server_db_res18.pth 与  ch_rec_server_crnn_res34.pth
调用 ocr_infer.py ：
python D:/Projects/PytorchOCR/tools/ocr_infer.py --det_path ../weights/ch_det_server_db_res18.pth --rec_path ../weights/ch_rec_server_crnn_res34.pth --img_path ../1.PNG

原图如下
![raw](https://user-images.githubusercontent.com/44104044/123062699-593b0380-d43f-11eb-840b-01a4f2560c98.PNG)
PytorchOCR结果
![pytorchOCR](https://user-images.githubusercontent.com/44104044/123062755-65bf5c00-d43f-11eb-9d97-e67f0eb11017.PNG)
Paddle结果
![paddle](https://user-images.githubusercontent.com/44104044/123062899-838cc100-d43f-11eb-909e-2f9711de63da.PNG)

请问这个效果是否正常？

安装库以及版本如下
Win10
Package            Version
------------------ -----------
addict             2.2.1
backcall           0.2.0
colorama           0.4.4
cycler             0.10.0
decorator          4.4.2
imageio            2.9.0
imgaug             0.4.0
ipython            7.24.1
ipython-genutils   0.2.0
jedi               0.18.0
kiwisolver         1.3.1
line-profiler      3.3.0
lmdb               1.2.1
matplotlib         3.4.2
matplotlib-inline  0.1.2
memory-profiler    0.58.0
networkx           2.5.1
numpy              1.18.4
opencv-python      4.2.0.34
parso              0.8.2
pickleshare        0.7.5
Pillow             8.2.0
pip                21.1.2
prompt-toolkit     3.0.19
psutil             5.8.0
pyclipper          1.1.0.post3
Pygments           2.9.0
pyparsing          2.4.7
python-dateutil    2.8.1
python-Levenshtein 0.12.2
PyWavelets         1.1.1
scikit-image       0.18.1
scipy              1.7.0
setuptools         57.0.0
Shapely            1.7.0
six                1.16.0
termcolor          1.1.0
tifffile           2021.6.14
torch              1.9.0
torchvision        0.10.0
tqdm               4.46.0
traitlets          5.0.5
typing-extensions  3.10.0.0
wcwidth            0.2.5

**Comment by Dajiang1202** [comment]
另外发现相同模型CRNN下，都使用CPU，paddle会快很多

**Comment by novioleo** [comment]
@Dajiang1202 感谢您的认真使用以及反馈。torchocr目前因为客观原因没法维护，所以里面的inference的预处理和后处理都不是特别棒。如果需要，你可以参考[Savior](https://github.com/novioleo/Savior)的中OCR算子的预处理和后处理。
另外torch和paddle在cpu上的性能相比，确实很差。这个我们一直都知道。cpu上部署的话，可以尝试ncnn或者tnn或者mnn之类，亦或者直接使用ppl。

**Comment by Dajiang1202** [comment]
> @Dajiang1202 感谢您的认真使用以及反馈。torchocr目前因为客观原因没法维护，所以里面的inference的预处理和后处理都不是特别棒。如果需要，你可以参考[Savior](https://github.com/novioleo/Savior)的中OCR算子的预处理和后处理。
> 另外torch和paddle在cpu上的性能相比，确实很差。这个我们一直都知道。cpu上部署的话，可以尝试ncnn或者tnn或者mnn之类，亦或者直接使用ppl。

感谢建议，后续都会尝试下部署
