### ISSUE TITLE
det_train训练正常，验证报错

### ISSUE THREAD

**Issue by eldrick-dai** [WenmuZhou/PytorchOCR#184]
2021-07-07 02:58:47,954 - torchocr - INFO - start evaluate
  0%|                                                                                             | 0/5603 [00:00<?, ?it/s]
2021-07-07 02:58:48,145 - torchocr - ERROR - Traceback (most recent call last):
  File "./tools/det_train.py", line 252, in train
    eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
  File "./tools/det_train.py", line 153, in evaluate
    boxes, scores = post_process(output.cpu().numpy(), batch_data['shape'], is_output_polygon=metric.is_output_polygon if hasattr(metric,'is_output_polygon') else False)
TypeError: __call__() got an unexpected keyword argument 'is_output_polygon'

2021-07-07 02:58:48,146 - torchocr - INFO - recall: 0
2021-07-07 02:58:48,146 - torchocr - INFO - precision: 0
2021-07-07 02:58:48,146 - torchocr - INFO - hmean: 0
2021-07-07 02:58:48,146 - torchocr - INFO - best_model_epoch: 0

**Comment by eldrick-dai** [comment]
干掉", is_output_polygon=metric.is_output_polygon if hasattr(metric,'is_output_polygon') else False" 后，开始报如下错误：
2021-07-07 03:21:57,186 - torchocr - INFO - start evaluate
  0%|                                                                                     | 1/5603 [00:00<12:45,  7.32it/s]
2021-07-07 03:21:57,328 - torchocr - ERROR - Traceback (most recent call last):
  File "./tools/det_train.py", line 252, in train
    eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
  File "./tools/det_train.py", line 150, in evaluate
    for batch_data in tqdm(val_loader):
  File "/home/pai/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/pai/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/admin/workspace/PytorchOCR/torchocr/datasets/DetCollateFN.py", line 27, in __call__
    v = torch.tensor(v)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by novioleo** [comment]
你debug看下v是什么，应该是你的数据有点问题哈。

**Comment by eldrick-dai** [comment]
> 你debug看下v是什么，应该是你的数据有点问题哈。

在转换前输出v：
if isinstance(v, np.ndarray):
                        print(v)
                        v = torch.tensor(v)
结果
2021-07-07 04:29:15,990 - torchocr - INFO - start evaluate
  0%|                                                                                             | 0/5603 [00:00<?, ?it/s][[[141 199]
  [237 201]
  [313 236]
  [357 283]
  [359 300]
  [309 261]
  [233 230]
  [140 231]]]
[list([[25, 13], [57, 71], [26, 92], [0, 34]])
 list([[264, 21], [296, 0], [300, 9], [272, 31]])
 list([[322, 0], [351, 25], [340, 31], [317, 9]])
 list([[287, 71], [330, 69], [334, 83], [284, 82]])
 list([[191, 103], [419, 103], [420, 148], [191, 144]])
 list([[0, 305], [14, 299], [28, 318], [47, 340], [31, 355], [11, 351], [5, 338], [0, 329]])
 list([[178, 289], [432, 289], [431, 326], [177, 323]])
 list([[212, 347], [395, 347], [396, 383], [213, 382]])]
  0%|                                                                                     | 1/5603 [00:00<12:59,  7.19it/s]
[list([[2, 292], [221, 284], [212, 345], [0, 349]])
 list([[336, 169], [560, 164], [559, 210], [336, 212]])
 list([[350, 268], [466, 246], [563, 248], [625, 266], [625, 300], [556, 282], [470, 284], [355, 303]])
 list([[572, 474], [590, 473], [594, 510], [575, 511]])]
2021-07-07 04:29:16,132 - torchocr - ERROR - Traceback (most recent call last):
  File "./tools/det_train.py", line 252, in train
    eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
  File "./tools/det_train.py", line 150, in evaluate
    for batch_data in tqdm(val_loader):
  File "/home/pai/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/pai/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/admin/workspace/PytorchOCR/torchocr/datasets/DetCollateFN.py", line 28, in __call__
    v = torch.tensor(v)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by novioleo** [comment]
你把坐标信息拿进来转换干啥。。你的数据处理有误，自己解决下哈~

**Comment by eldrick-dai** [comment]
我用了ocr-dataset中Art数据集，只改动了dataset的json文件的位置，train和eval临时用同一个文件，其余未动，所以不太清楚验证集的坐标转换是直接过滤掉吗？

**Comment by novioleo** [comment]
你可以自己试试在train模式下，这个v是啥。理论上来说其实很简单，只需要你对v进行变换成np array，然后就能执行torch tensor了。

**Comment by eldrick-dai** [comment]
> 你可以自己试试在train模式下，这个v是啥。理论上来说其实很简单，只需要你对v进行变换成np array，然后就能执行torch tensor了。

是的，我尝试了做如下改变：
if isinstance(v, np.ndarray):
                        print('start')
                        print(v)
                        print('tnsforming:')
                        nv = []
                        for d in v:
                            d = np.array(d)
                            nv.append(d)
                        print('nv:')
                        print(nv)
                        v = torch.tensor(nv)
                        print(v)
                        print('end')
结果在转换的时候报数据维度问题，Art数据集中部分数据并不是4个点组成的矩形框，是一些是多个点组成的多边形。
以下是原始读取数据：
{'img_path': '/home/admin/workspace/data/dataset/Art/detection/train_images/gt_1234.jpg', 'img_name': 'gt_1234.jpg', 'text_polys': array([list([[2, 292], [221, 284], [212, 345], [0, 349]]),
       list([[336, 169], [560, 164], [559, 210], [336, 212]]),
       list([[350, 268], [466, 246], [563, 248], [625, 266], [625, 300], [556, 282], [470, 284], [355, 303]]),
       list([[572, 474], [590, 473], [594, 510], [575, 511]])],
      dtype=object), 'texts': ['龙虾厅', '华夏良子', '中国足道·SPA养生', '###'], 'ignore_tags': [False, False, False, True], 'img': tensor([[[ 2.2489,  2.2489,  2.2489,  ..., -0.7650, -0.6109, -0.6281],
         [ 2.2489,  2.2489,  2.2489,  ..., -0.9020, -1.0048, -1.2617],
         [ 2.2489,  2.2489,  2.2489,  ..., -1.0048, -1.1589, -1.3815],
         ...,
         [ 0.2282,  0.2453,  0.2282,  ..., -1.9124, -1.8782, -1.8439],
         [ 0.1597,  0.1768,  0.1768,  ..., -1.9124, -1.8782, -1.8610],
         [ 0.1597,  0.1597,  0.1597,  ..., -1.9295, -1.8953, -1.8610]],

        [[ 2.4286,  2.4286,  2.4286,  ..., -0.4426, -0.2850, -0.2675],
         [ 2.4286,  2.4286,  2.4286,  ..., -0.5651, -0.6702, -0.9153],
         [ 2.4286,  2.4286,  2.4286,  ..., -0.6527, -0.7927, -1.0203],
         ...,
         [ 0.0126,  0.0301,  0.0301,  ..., -1.7031, -1.6856, -1.6681],
         [-0.0749, -0.0574, -0.0574,  ..., -1.7031, -1.6856, -1.6681],
         [-0.0749, -0.0749, -0.0749,  ..., -1.7206, -1.7031, -1.6856]],

        [[ 2.6400,  2.6400,  2.6400,  ..., -0.2184, -0.0615, -0.0441],
         [ 2.6400,  2.6400,  2.6400,  ..., -0.3404, -0.4450, -0.6890],
         [ 2.6400,  2.6400,  2.6400,  ..., -0.4275, -0.5670, -0.7936],
         ...,
         [-0.0964, -0.0964, -0.0964,  ..., -1.5953, -1.5604, -1.5604],
         [-0.1835, -0.1661, -0.1661,  ..., -1.5953, -1.5604, -1.5430],
         [-0.1835, -0.1661, -0.1661,  ..., -1.6127, -1.5779, -1.5604]]]), 'shape': [550, 693]}

以下是错误打印的日志：
start
[list([[2, 292], [221, 284], [212, 345], [0, 349]])
 list([[336, 169], [560, 164], [559, 210], [336, 212]])
 list([[350, 268], [466, 246], [563, 248], [625, 266], [625, 300], [556, 282], [470, 284], [355, 303]])
 list([[572, 474], [590, 473], [594, 510], [575, 511]])]
tnsforming:
nv:
  0%|                                                                                     | 1/5603 [00:00<13:54,  6.72it/s][array([[  2, 292],
       [221, 284],
       [212, 345],
       [  0, 349]]), array([[336, 169],
       [560, 164],
       [559, 210],
       [336, 212]]), array([[350, 268],
       [466, 246],
       [563, 248],
       [625, 266],
       [625, 300],
       [556, 282],
       [470, 284],
       [355, 303]]), array([[572, 474],
       [590, 473],
       [594, 510],
       [575, 511]])]
  0%|                                                                                     | 1/5603 [00:00<13:58,  6.68it/s]
2021-07-07 09:15:47,666 - torchocr - ERROR - Traceback (most recent call last):
  File "./tools/det_train.py", line 252, in train
    eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
  File "./tools/det_train.py", line 150, in evaluate
    for batch_data in tqdm(val_loader):
  File "/home/pai/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/pai/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/admin/workspace/pytorch-ocr/torchocr/datasets/DetCollateFN.py", line 37, in __call__
    v = torch.tensor(nv)
ValueError: expected sequence of length 4 at dim 1 (got 8)

**Comment by eldrick-dai** [comment]
> > 你可以自己试试在train模式下，这个v是啥。理论上来说其实很简单，只需要你对v进行变换成np array，然后就能执行torch tensor了。
> 
> 是的，我尝试了做如下改变：
> if isinstance(v, np.ndarray):
> print('start')
> print(v)
> print('tnsforming:')
> nv = []
> for d in v:
> d = np.array(d)
> nv.append(d)
> print('nv:')
> print(nv)
> v = torch.tensor(nv)
> print(v)
> print('end')
> 结果在转换的时候报数据维度问题，Art数据集中部分数据并不是4个点组成的矩形框，是一些是多个点组成的多边形。
> 以下是原始读取数据：
> {'img_path': '/home/admin/workspace/data/dataset/Art/detection/train_images/gt_1234.jpg', 'img_name': 'gt_1234.jpg', 'text_polys': array([list([[2, 292], [221, 284], [212, 345], [0, 349]]),
> list([[336, 169], [560, 164], [559, 210], [336, 212]]),
> list([[350, 268], [466, 246], [563, 248], [625, 266], [625, 300], [556, 282], [470, 284], [355, 303]]),
> list([[572, 474], [590, 473], [594, 510], [575, 511]])],
> dtype=object), 'texts': ['龙虾厅', '华夏良子', '中国足道·SPA养生', '###'], 'ignore_tags': [False, False, False, True], 'img': tensor([[[ 2.2489, 2.2489, 2.2489, ..., -0.7650, -0.6109, -0.6281],
> [ 2.2489, 2.2489, 2.2489, ..., -0.9020, -1.0048, -1.2617],
> [ 2.2489, 2.2489, 2.2489, ..., -1.0048, -1.1589, -1.3815],
> ...,
> [ 0.2282, 0.2453, 0.2282, ..., -1.9124, -1.8782, -1.8439],
> [ 0.1597, 0.1768, 0.1768, ..., -1.9124, -1.8782, -1.8610],
> [ 0.1597, 0.1597, 0.1597, ..., -1.9295, -1.8953, -1.8610]],
> 
> ```
>     [[ 2.4286,  2.4286,  2.4286,  ..., -0.4426, -0.2850, -0.2675],
>      [ 2.4286,  2.4286,  2.4286,  ..., -0.5651, -0.6702, -0.9153],
>      [ 2.4286,  2.4286,  2.4286,  ..., -0.6527, -0.7927, -1.0203],
>      ...,
>      [ 0.0126,  0.0301,  0.0301,  ..., -1.7031, -1.6856, -1.6681],
>      [-0.0749, -0.0574, -0.0574,  ..., -1.7031, -1.6856, -1.6681],
>      [-0.0749, -0.0749, -0.0749,  ..., -1.7206, -1.7031, -1.6856]],
> 
>     [[ 2.6400,  2.6400,  2.6400,  ..., -0.2184, -0.0615, -0.0441],
>      [ 2.6400,  2.6400,  2.6400,  ..., -0.3404, -0.4450, -0.6890],
>      [ 2.6400,  2.6400,  2.6400,  ..., -0.4275, -0.5670, -0.7936],
>      ...,
>      [-0.0964, -0.0964, -0.0964,  ..., -1.5953, -1.5604, -1.5604],
>      [-0.1835, -0.1661, -0.1661,  ..., -1.5953, -1.5604, -1.5430],
>      [-0.1835, -0.1661, -0.1661,  ..., -1.6127, -1.5779, -1.5604]]]), 'shape': [550, 693]}
> ```
> 
> 以下是错误打印的日志：
> start
> [list([[2, 292], [221, 284], [212, 345], [0, 349]])
> list([[336, 169], [560, 164], [559, 210], [336, 212]])
> list([[350, 268], [466, 246], [563, 248], [625, 266], [625, 300], [556, 282], [470, 284], [355, 303]])
> list([[572, 474], [590, 473], [594, 510], [575, 511]])]
> tnsforming:
> nv:
> 0%| | 1/5603 [00:00<13:54, 6.72it/s][array([[ 2, 292],
> [221, 284],
> [212, 345],
> [ 0, 349]]), array([[336, 169],
> [560, 164],
> [559, 210],
> [336, 212]]), array([[350, 268],
> [466, 246],
> [563, 248],
> [625, 266],
> [625, 300],
> [556, 282],
> [470, 284],
> [355, 303]]), array([[572, 474],
> [590, 473],
> [594, 510],
> [575, 511]])]
> 0%| | 1/5603 [00:00<13:58, 6.68it/s]
> 2021-07-07 09:15:47,666 - torchocr - ERROR - Traceback (most recent call last):
> File "./tools/det_train.py", line 252, in train
> eval_dict = evaluate(net, eval_loader, to_use_device, logger, post_process, metric)
> File "./tools/det_train.py", line 150, in evaluate
> for batch_data in tqdm(val_loader):
> File "/home/pai/lib/python3.6/site-packages/tqdm/std.py", line 1178, in **iter**
> for obj in iterable:
> File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> data = self._next_data()
> File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
> return self._process_data(data)
> File "/home/pai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> data.reraise()
> File "/home/pai/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
> raise self.exc_type(msg)
> ValueError: Caught ValueError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/pai/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/home/admin/workspace/pytorch-ocr/torchocr/datasets/DetCollateFN.py", line 37, in **call**
> v = torch.tensor(nv)
> ValueError: expected sequence of length 4 at dim 1 (got 8)

确实换了个数据集，使用icdar2015后就正常了，那么类似Art数据集（多于4组点）要怎么处理才可以用呢？

**Comment by novioleo** [comment]
你对比下两个数据集的label的格式，对应的处理下~~

**Comment by w452144816** [comment]
https://github.com/WenmuZhou/PytorchOCR/blob/master/torchocr/datasets/DetDataSet.py#L86   这里的 np.array(polygons)换成polygons

**Comment by w452144816** [comment]
art 的 gt_2805 有问题
