### ISSUE TITLE
使用提供的预训练模型进行文本检测出错

### ISSUE THREAD

**Issue by hhhhhhogan** [WenmuZhou/PytorchOCR#188]
![image](https://user-images.githubusercontent.com/40531744/128448455-232c09ec-71f1-408a-8fae-1a717c3477db.png)
RuntimeError: Error(s) in loading state_dict for ResNet:
        Missing key(s) in state_dict: "conv1.0.conv.weight", "conv1.0.bn.weight", "conv1.0.bn.bias", "conv1.0.bn.running_mean", "conv1.0.bn.running_var", "conv1.1.conv.weight", "conv1.1.bn.weight", "conv1.1.bn.bias", "conv1.1.bn.running_mean", "conv1.1.bn.running_var", "conv1.2.conv.weight", "conv1.2.bn.weight", "conv1.2.bn.bias", "conv1.2.bn.running_mean", "conv1.2.bn.running_var", "stages.0.0.conv0.conv.weight", "stages.0.0.conv0.bn.weight", "stages.0.0.conv0.bn.bias", "stages.0.0.conv0.bn.running_mean", "stages.0.0.conv0.bn.running_var", "stages.0.0.conv1.conv.weight", "stages.0.0.conv1.bn.weight", "stages.0.0.conv1.bn.bias", "stages.0.0.conv1.bn.running_mean", "stages.0.0.conv1.bn.running_var", "stages.0.0.shortcut.conv.conv.weight", "stages.0.0.shortcut.conv.bn.weight", "stages.0.0.shortcut.conv.bn.bias", "stages.0.0.shortcut.conv.bn.running_mean", "stages.0.0.shortcut.conv.bn.running_var", "stages.0.1.conv0.conv.weight", "stages.0.1.conv0.bn.weight", "stages.0.1.conv0.bn.bias", "stages.0.1.conv0.bn.running_mean", "stages.0.1.conv0.bn.running_var", "stages.0.1.conv1.conv.weight", "stages.0.1.conv1.bn.weight", "stages.0.1.conv1.bn.bias", "stages.0.1.conv1.bn.running_mean", "stages.0.1.conv1.bn.running_var", "stages.1.0.conv0.conv.weight", "stages.1.0.conv0.bn.weight", "stages.1.0.conv0.bn.bias", "stages.1.0.conv0.bn.running_mean", "stages.1.0.conv0.bn.running_var", "stages.1.0.conv1.conv.weight", "stages.1.0.conv1.bn.weight", "stages.1.0.conv1.bn.bias", "stages.1.0.conv1.bn.running_mean", "stages.1.0.conv1.bn.running_var", "stages.1.0.shortcut.conv.conv.weight", "stages.1.0.shortcut.conv.bn.weight", "stages.1.0.shortcut.conv.bn.bias", "stages.1.0.shortcut.conv.bn.running_mean", "stages.1.0.shortcut.conv.bn.running_var", "stages.1.1.conv0.conv.weight", "stages.1.1.conv0.bn.weight", "stages.1.1.conv0.bn.bias", "stages.1.1.conv0.bn.running_mean", "stages.1.1.conv0.bn.running_var", "stages.1.1.conv1.conv.weight", "stages.1.1.conv1.bn.weight", "stages.1.1.conv1.bn.bias", "stages.1.1.conv1.bn.running_mean", "stages.1.1.conv1.bn.running_var", "stages.2.0.conv0.conv.weight", "stages.2.0.conv0.bn.weight", "stages.2.0.conv0.bn.bias", "stages.2.0.conv0.bn.running_mean", "stages.2.0.conv0.bn.running_var", "stages.2.0.conv1.conv.weight", "stages.2.0.conv1.bn.weight", "stages.2.0.conv1.bn.bias", "stages.2.0.conv1.bn.running_mean", "stages.2.0.conv1.bn.running_var", "stages.2.0.shortcut.conv.conv.weight", "stages.2.0.shortcut.conv.bn.weight", "stages.2.0.shortcut.conv.bn.bias", "stages.2.0.shortcut.conv.bn.running_mean", "stages.2.0.shortcut.conv.bn.running_var", "stages.2.1.conv0.conv.weight", "stages.2.1.conv0.bn.weight", "stages.2.1.conv0.bn.bias", "stages.2.1.conv0.bn.running_mean", "stages.2.1.conv0.bn.running_var", "stages.2.1.conv1.conv.weight", "stages.2.1.conv1.bn.weight", "stages.2.1.conv1.bn.bias", "stages.2.1.conv1.bn.running_mean", "stages.2.1.conv1.bn.running_var", "stages.3.0.conv0.conv.weight", "stages.3.0.conv0.bn.weight", "stages.3.0.conv0.bn.bias", "stages.3.0.conv0.bn.running_mean", "stages.3.0.conv0.bn.running_var", "stages.3.0.conv1.conv.weight", "stages.3.0.conv1.bn.weight", "stages.3.0.conv1.bn.bias", "stages.3.0.conv1.bn.running_mean", "stages.3.0.conv1.bn.running_var", "stages.3.0.shortcut.conv.conv.weight", "stages.3.0.shortcut.conv.bn.weight", "stages.3.0.shortcut.conv.bn.bias", "stages.3.0.shortcut.conv.bn.running_mean", "stages.3.0.shortcut.conv.bn.running_var", "stages.3.1.conv0.conv.weight", "stages.3.1.conv0.bn.weight", "stages.3.1.conv0.bn.bias", "stages.3.1.conv0.bn.running_mean", "stages.3.1.conv0.bn.running_var", "stages.3.1.conv1.conv.weight", "stages.3.1.conv1.bn.weight", "stages.3.1.conv1.bn.bias", "stages.3.1.conv1.bn.running_mean", "stages.3.1.conv1.bn.running_var". 
        Unexpected key(s) in state_dict: "cfg", "state_dict". 

请问怎么解决呢，使用的预训练模型是resnet18、resnet50都试过

**Comment by novioleo** [comment]
在state_dict里面。。。走点心好吧。。。

**Comment by hhhhhhogan** [comment]
> 在state_dict里面。。。走点心好吧。。。

确实，大佬解决了。。。。
