### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by cccusername** [WenmuZhou/PytorchOCR#194]
你好，我这边在用自己数据训练时候报错了，好像是yin'w因为找不到数据，但是我这边的数据格式确实就是 文件名+\t+标签 的格式，而且图片确实也存在，麻烦看一下呢，谢谢
![image](https://user-images.githubusercontent.com/33566026/131469295-fc0ce1b6-263f-4dac-b9ce-c5f575da8430.png)
![image](https://user-images.githubusercontent.com/33566026/131469402-ce5020b0-b1e0-4e4c-99f1-f7ca491d50b6.png)

**Comment by gaofei979** [comment]
我也遇到了这个问题，请问怎么解决？

**Comment by kjcx100** [comment]
我用lmdb数据集也有问题，报一样的错误，RecLmdbDataset 这个又咋改啊？
