### ISSUE TITLE
rec_train 的bug

### ISSUE THREAD

**Issue by ymmshi** [WenmuZhou/PytorchOCR#195]
建议将 
https://github.com/WenmuZhou/PytorchOCR/blob/4582cf1a1e3a97b54b1e54763a4b09e409186a00/tools/rec_train.py#L253
改为
`if global_step >= train_options['val_interval'] and global_step % train_options['val_interval'] == 0:`
否则当 (i+1) < train_options['val_interval']时，永远不会触发evaluate(),也不会保存best_model.

另外，https://github.com/WenmuZhou/PytorchOCR/blob/4582cf1a1e3a97b54b1e54763a4b09e409186a00/tools/rec_train.py#L9
中的“陆径”字写错了

**Comment by novioleo** [comment]
哈哈哈哈。马上改。感谢。
