### ISSUE TITLE
在自己的训练集上训练时，准确率一直为0

### ISSUE THREAD

**Issue by dsddca** [WenmuZhou/PytorchOCR#197]
用的是百度中文的数据集，截取了一部分当数据集。词典共1420字加上blank是1421个，pytorch版本是1.60，是8月初拉取全部的代码，rec_config_train.py只调整了训练集测试集和字典的路径，学习率改为0.0003，和nc_class改为1421。我想问一下这种问题该怎么解决？

**Comment by novioleo** [comment]
训练了多久？

**Comment by dsddca** [comment]
完整的200轮以及分散的10-50个epoch，然后我下了百度云里的测试用lmdb数据集，训练了5个epoch也全都为0

**Comment by key220888** [comment]
蹲，老哥解决了这个问题吗？我也出现了相同的问题

**Comment by key220888** [comment]
> 蹲，老哥解决了这个问题吗？我也出现了相同的问题

自己尝试了一下，用10个图片的玩具集训练，如果只训练一二十个epoch是没有用的，100个左右在训练集上能达到0.7-0.8的准确率，所以还是要增加epochs
