### ISSUE TITLE
finetune rec_model

### ISSUE THREAD

**Issue by ltm920716** [WenmuZhou/PytorchOCR#200]
hello,
 识别部分是ocr的难点，请问怎样才能在提供的训练好的模型 ch_rec_server_crnn_res34.pth 上直接做finetune呢，从头训练缺少很多数据集，并且也不是很好训练，谢谢

**Comment by novioleo** [comment]
只保留backbone，bn开启eval。

**Comment by ltm920716** [comment]
@novioleo 
感谢回复，目前问题是模型 state_dict 可以对不上

![image](https://user-images.githubusercontent.com/12007227/135227665-72aba8b3-6600-4983-ac6e-f934670c0ffc.png)
![image](https://user-images.githubusercontent.com/12007227/135227752-696eb51c-b5ab-4d7f-94db-158ed181067c.png)

请问这个是需要人为转换一下key就可以么，谢谢

**Comment by novioleo** [comment]
model.module.load_state_dict()不就解决了吗。。

**Comment by ltm920716** [comment]
@novioleo 
是的，是因为dataparrallel的问题，git上的代码需要需要优化一下

![image](https://user-images.githubusercontent.com/12007227/135230378-6c96f6bf-e679-43cc-95af-d48e0743210f.png)

加载后续还是有一些其他问题（optimize，dataloader等），我尝试解决，非常感谢回复
