### ISSUE TITLE
选择训练参数

### ISSUE THREAD

**Issue by ltm920716** [WenmuZhou/PytorchOCR#201]
hello，
训练脚本里有一个地方没有研究明白，还麻烦指点一下

params_to_train = get_fine_tune_params(net, train_options['fine_tune_stage'])
optimizer = build_optimizer(net.parameters(), cfg['optimizer'])

def get_fine_tune_params(net, finetune_stage):
    """
    获取需要优化的参数
    Args:
        net:
    Returns: 需要优化的参数
    """
    to_return_parameters = []
    for stage in finetune_stage:
        attr = getattr(net.module, stage, None)
        for element in attr.parameters():
            to_return_parameters.append(element)
    return to_return_parameters

这个是获取要 finetune 的参数，但是这个函数里除了获取到参数并没有做额外的操作，是我的理解有误么，还是说optimizer的传参写错了，谢谢

**Comment by novioleo** [comment]
@ltm920716 这个临时测试代码估计被他们提交上来了，忘记把params_to_train放到下面的去了，下面还是用的全部参数。
