### ISSUE TITLE
识别网络没有效果

### ISSUE THREAD

**Issue by zhanghongsir** [WenmuZhou/PytorchOCR#202]
使用icdar2015识别网络效果很差，训练完整的200轮，不用预训练模型，使用mobilenet和resnet34效果都很差，不知道什么原因。

**Comment by yangh-zzf-itcast** [comment]
> 使用icdar2015识别网络效果很差，训练完整的200轮，不用预训练模型，使用mobilenet和resnet34效果都很差，不知道什么原因。

+1，训练到了99接近1了，但是识别只有26%左右，是过拟合了么

**Comment by zhanghongsir** [comment]
> 



> > 使用icdar2015识别网络效果很差，训练完整的200轮，不用预训练模型，使用mobilenet和resnet34效果都很差，不知道什么原因。
> 
> +1，训练到了99接近1了，但是识别只有26%左右，是过拟合了么

应该是数据集太小了，这个数据集很难有效果，换个大点的数据集会好很多

**Comment by yangh-zzf-itcast** [comment]
> > 
> 
> > > 使用icdar2015识别网络效果很差，训练完整的200轮，不用预训练模型，使用mobilenet和resnet34效果都很差，不知道什么原因。
> > 
> > 
> > +1，训练到了99接近1了，但是识别只有26%左右，是过拟合了么
> 
> 应该是数据集太小了，这个数据集很难有效果，换个大点的数据集会好很多

好的哈，谢谢，我换百度那个试试看
