### ISSUE TITLE
关于训练时精确度的问题

### ISSUE THREAD

**Issue by liangcaihua** [WenmuZhou/PytorchOCR#203]
到第2轮的时候，达到了0.08
使用了baidu数据集， 修改了如下参数：
 'backbone': {"type": "ResNet", 'model_name': 'small', 'layers': 18},
    'neck': {"type": 'PPaddleRNN', "hidden_size": 128},
    'head': {"type": "CTC", 'n_class': 6624},

重点是n_class，默认是93，训练一会就报错，找了很久才发现这个问题

2021-10-15 21:12:44,457 - torchocr - INFO - [2/200] - [200/4128] - lr:0.001 - loss:3.5757 - acc:0.0800 - norm_edit_dis:0.3539 - time:25.4649

**Comment by yangh-zzf-itcast** [comment]
> 

兄弟，這個n_class是不是看使用那個alpha.txt，然後再加上空格1個？

**Comment by yangh-zzf-itcast** [comment]
> 到第2轮的时候，达到了0.08 使用了baidu数据集， 修改了如下参数： 'backbone': {"type": "ResNet", 'model_name': 'small', 'layers': 18}, 'neck': {"type": 'PPaddleRNN', "hidden_size": 128}, 'head': {"type": "CTC", 'n_class': 6624},
> 
> 重点是n_class，默认是93，训练一会就报错，找了很久才发现这个问题
> 
> 2021-10-15 21:12:44,457 - torchocr - INFO - [2/200] - [200/4128] - lr:0.001 - loss:3.5757 - acc:0.0800 - norm_edit_dis:0.3539 - time:25.4649

百度数据集标签的英文字符感觉跟字母表里的英文字符不太一样，这个对训练有影响么

**Comment by novioleo** [comment]
当然。

**Comment by yangh-zzf-itcast** [comment]
> 当然。

训练得到的模型和验证时候用的字母表是不是要一样？比如train时候用的字母表跟infer的时候用的字母表字体不一样就准确率不行了么？

**Comment by bowenliu1996** [comment]
你还有训练百度数据集的代码吗，我的这个加载不进去数据。
