### ISSUE TITLE
random_crop_data crop_area function get TypeError

### ISSUE THREAD

**Issue by morestart** [WenmuZhou/PytorchOCR#205]
i use [LSVT](https://pan.baidu.com/s/1mRepVEvMa-U4e9ThiskVXg) dataset, i got this error... 
`TypeError: loop of ufunc does not support argument 0 of type numpy.float32 which has no callable rint method`

https://github.com/WenmuZhou/PytorchOCR/blob/af80609277721c711aec6eba8e2decc9b1c2cc29/torchocr/datasets/det_modules/random_crop_data.py#L115

I added the following to this line

```Python
for points in text_polys:
    points = np.array(points)
    points = points.astype(float)
    points = np.round(points, decimals=0).astype(np.int32)
```

it works.

**Comment by novioleo** [comment]
fine.
