### ISSUE TITLE
訓練耗時問題？

### ISSUE THREAD

**Issue by yangh-zzf-itcast** [WenmuZhou/PytorchOCR#210]
您好，麻煩問一下，訓練時候，每個step的耗時相差很大是因爲什麽呢？
![image](https://user-images.githubusercontent.com/45489193/144530395-541fadef-c33f-43a3-83ce-153311e34e6e.png)

**Comment by yangh-zzf-itcast** [comment]
另外同个epoch中每个step的准确率会波动比较大，是啥原因？
![image](https://user-images.githubusercontent.com/45489193/144574460-44047892-2182-422f-a283-f1fa4535c304.png)

**Comment by novioleo** [comment]
1. 耗时，你换台机器看看有没有类似情况。一般就是你在跑其他任务导致。
2. 那是每个batch的acc，波动完全正常

**Comment by yangh-zzf-itcast** [comment]
> 1. 耗时，你换台机器看看有没有类似情况。一般就是你在跑其他任务导致。
> 2. 那是每个batch的acc，波动完全正常

好的，我再试试看，非常感谢！对了麻烦问一下这个模型的图像输入高度对结果影响大么，我试了以下您放的预训练模型，差不多的文字，一个高度32，一个高度39，结果精度相差很大。
这是高度32的，结果准确性很高
![image](https://user-images.githubusercontent.com/45489193/144703682-c6eedad5-32af-4bb0-b912-cc015a49bf4e.png)
这个是39，结果相差很大。
![image](https://user-images.githubusercontent.com/45489193/144703698-3ac1059e-fc97-43af-921b-a50ceff997a2.png)
