### ISSUE TITLE
rec dataset split error

### ISSUE THREAD

**Issue by morestart** [WenmuZhou/PytorchOCR#215]
https://github.com/WenmuZhou/PytorchOCR/blob/0b2b3a67814ae40b20f3814d6793f5d75d644e38/torchocr/datasets/RecDataSet.py#L40

in document, txt use \t to split data.....

and img path is error too

https://github.com/WenmuZhou/PytorchOCR/blob/0b2b3a67814ae40b20f3814d6793f5d75d644e38/torchocr/datasets/RecDataSet.py#L43

**Comment by bowenliu1996** [comment]
how to solve it？please help me . I have the same question!!!

**Comment by morestart** [comment]
@bowenliu1996 

params = m_line.split('\t') 
m_image_name = m_image_name

**Comment by bowenliu1996** [comment]
Thanks
