### ISSUE TITLE
CRNN识别测试精度问题

### ISSUE THREAD

**Issue by yangh-zzf-itcast** [WenmuZhou/PytorchOCR#219]
您好，我使用syn360W的数据库99：1，切分了训练集和验证集。然后训练了100个左右epoch，验证集准确率在87%左右。然后我使用推断脚本，测试验证集的图片时都效果不错。
![image](https://user-images.githubusercontent.com/45489193/149931921-8b2e9a97-557e-4416-a5bd-5f9fa69ce427.png)
![image](https://user-images.githubusercontent.com/45489193/149931886-2ecb86c4-4f97-4865-b137-4111a05597aa.png)
但是网页中随意截取了一段差不多的文字。就会出现比较大的差异。截取的文字跟训练集样式感觉差不多，但是效果不好，请问这个可能是模型的泛化能力不好，还是什么其他后处理导致的呢？
![image](https://user-images.githubusercontent.com/45489193/149932073-b1d5a949-8630-4880-aa58-15dae01b47e0.png)
![image](https://user-images.githubusercontent.com/45489193/149932030-18880661-198a-4a76-be0f-9b81ceaf00fc.png)

**Comment by novioleo** [comment]
输入到网络的图像只需要等高变换即可。不要直接resize到目标大小

**Comment by yangh-zzf-itcast** [comment]
> infer的时候输入图像是调用的这个函数，把高度resize到config里面设置的32了。应该就是您说得等高变换吧？
    def resize_with_specific_height(self, _img):
        """
        将图像resize到指定高度
        :param _img:    待resize的图像
        :return:    resize完成的图像
        """
        resize_ratio = self.config.input_h / _img.shape[0]
        return cv2.resize(_img, (0, 0), fx=resize_ratio, fy=resize_ratio, interpolation=cv2.INTER_LINEAR)

**Comment by yangh-zzf-itcast** [comment]
> 

意思是只要把高度变换到对应训练的高度，然后宽度不用变是么？

**Comment by Bourne-M** [comment]
> 

100个epoch才87%吗？使用预训练模型了吗？

**Comment by yangh-zzf-itcast** [comment]
> > 
> 
> 100个epoch才87%吗？使用预训练模型了吗？
没有使用哎。直接训练的。backbone用的mobilenetv3。预训练模型是用哪个数据集训的？

**Comment by yangh-zzf-itcast** [comment]
> > 
> 
> 100个epoch才87%吗？使用预训练模型了吗？

识别的预训练模型是通过resume加载么？

**Comment by Bourne-M** [comment]
> > > 
> > 
> > 
> > 100个epoch才87%吗？使用预训练模型了吗？
> > 没有使用哎。直接训练的。backbone用的mobilenetv3。预训练模型是用哪个数据集训的？

可以用imagenet的预训练模型，配置文件中 backbone pretrained 设置为True

**Comment by yangh-zzf-itcast** [comment]
那预训练模型在那里加载哈？是要自己写么？因为我只看到resume那里有加载。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yfzhou ***@***.***&gt;
发送时间: 2022年1月20日 16:51
收件人: WenmuZhou/PytorchOCR ***@***.***&gt;
抄送: yangh-zzf-itcast ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WenmuZhou/PytorchOCR] CRNN识别测试精度问题 (Issue #219)





     
100个epoch才87%吗？使用预训练模型了吗？
 没有使用哎。直接训练的。backbone用的mobilenetv3。预训练模型是用哪个数据集训的？
   
可以用imagenet的预训练模型，配置文件中 backbone pretrained 设置为True
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aibohang** [comment]
同问，请问只看到config文件里有加载pretrained 设置为True,但是没有加载权重的路径，请问在哪个地方，还是说设置pretrained 设置为True代码会自动进行加载？

**Comment by huangxin168** [comment]
> 同问，请问只看到config文件里有加载pretrained 设置为True,但是没有加载权重的路径，请问在哪个地方，还是说设置pretrained 设置为True代码会自动进行加载？

目前没看到发布rec的pretrained，只看到det的
