### ISSUE TITLE
训练报错cv2.contourArea

### ISSUE THREAD

**Issue by DrewdropLife** [WenmuZhou/PytorchOCR#220]
你好！我使用了你网盘中提供的icdar2015数据集进行训练，但是MakeShrinkMap.py中如下代码报错：
`

    def validate_polygons(self, polygons, ignore_tags, h, w):
        '''
        polygons (numpy.array, required): of shape (num_instances, num_points, 2)
        '''
        if len(polygons) == 0:
            return polygons, ignore_tags

        assert len(polygons) == len(ignore_tags)

        for polygon in polygons:
            polygon[:, 0] = np.clip(polygon[:, 0], 0, w - 1)
            polygon[:, 1] = np.clip(polygon[:, 1], 0, h - 1)

        for i in range(len(polygons)):
            print(type(polygons[i]), polygons[i])
            area = self.polygon_area(polygons[i])
            if abs(area) < 1:
                ignore_tags[i] = True
            if area > 0:
                polygons[i] = polygons[i][::-1, :]
        return polygons, ignore_tags

    def polygon_area(self, polygon):
        return cv2.contourArea(polygon)
`
上述的cv2.contourArea在计算任意输入时都会报错，报错信息如下：
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'contourArea'

输入的polygon如下：
[[479.51342773, 330.86141968],
 [466.64575195, 329.01113892],
 [465.08013916, 339.8991394 ],
 [477.94781494, 341.74942017]]

可以告诉我这是什么原因吗？我使用的opencv版本是4.1.0

**Comment by novioleo** [comment]
用3.4

**Comment by DrewdropLife** [comment]
你好，我在icdar2015的检测 测试集 上同时进行训练和测试，200个epoch过后，最高精度只有0.69，是什么地方出问题了吗？

**Comment by DrewdropLife** [comment]
> 用3.4

你好，我在icdar2015的检测 测试集 上同时进行训练和测试，200个epoch过后，最高精度只有0.69，是什么地方出问题了吗？

**Comment by novioleo** [comment]
> 

使用pretrain，配置lrs。调整lr。
