### ISSUE TITLE
纵向文本识别率效果差

### ISSUE THREAD

**Issue by risemeup** [WenmuZhou/PytorchOCR#233]
https://github.com/WenmuZhou/PytorchOCR/blob/57e6245d478a8d8470d040574532bb96c0275024/tools/ocr_infer.py#L38-L41
当检测到纵向文本的时候将会旋转90度，但有些情况旋转之后刚好是完全颠倒的文本，导致识别出错。请问这个问题有没有方法解决呢。

**Comment by Bourne-M** [comment]
加一个 0和180分类 的分类模型

**Comment by huangxin168** [comment]
> 加一个 0和180分类 的分类模型

大佬，好事做到底，考虑在这个项目里增加分类模型吗？
