### ISSUE TITLE
random_crop_data.py中的split_regions函数，bug ?

### ISSUE THREAD

**Issue by zhongwenkun886** [WenmuZhou/PytorchOCR#235]
函数里的实现没有考虑到axis的结尾处，即 regions 不包括最后一个连续区域，不知道我的理解是否正确。类似的问题在paddleOCR也有，见 https://github.com/PaddlePaddle/PaddleOCR/issues/1940

**Comment by SLTK1** [comment]
遇到过相同的问题https://github.com/WenmuZhou/DBNet.pytorch/issues/122
