### ISSUE TITLE
关于文本识别中使用自己数据集训练精度一直为0的问题

### ISSUE THREAD

**Issue by qiuchun** [WenmuZhou/PytorchOCR#238]
使用自己构建的数据集200张进行训练，6000epochs，直到训练结束， eval acc的数值一直都是0，这个是什么原因导致的，有何办法能够解决啊，有没有遇到同样问题的朋友或者大佬来解答一下啊，跪谢！ [
![Uploading 11111111111121.png…]()
](url)

**Comment by Tomhardy13** [comment]
请问下你训练的精度也是0吗？

**Comment by huangxin168** [comment]
> 

训练都没收敛，训了个寂寞。。。
