### ISSUE TITLE
身份证识别

### ISSUE THREAD

**Issue by LiquorPerfect** [WenmuZhou/PytorchOCR#243]
您好，请教一下，对身份证做结构化，对送入DBnet之前对图片进行矫正，有哪些推荐的方法嘛？
还有就是身份证字符识别，会有少数名族字符，比如蒙古文，藏文等，有什么好的方法可以去除嘛？
谢谢。

**Comment by yangy996** [comment]
参考这篇文章改成多分类网络
https://blog.csdn.net/YY007H/article/details/124491217
