### ISSUE TITLE
请问如何训练pse-net？

### ISSUE THREAD

**Issue by tiamjiakun** [WenmuZhou/PytorchOCR#245]
我在运行det_train_pse时报错：NameError: name 'pse_postprocess' is not defined
pse的训练部分是不是还不完整？

**Comment by Bourne-M** [comment]
https://github.com/WenmuZhou/PytorchOCR/blob/808932297983172e2b5c39138469eaa6a9a02907/torchocr/postprocess/__init__.py#L7 
这个放开试试，不过要先自己编译pse文件夹里面的东西

**Comment by tiamjiakun** [comment]
> https://github.com/WenmuZhou/PytorchOCR/blob/808932297983172e2b5c39138469eaa6a9a02907/torchocr/postprocess/__init__.py#L7
> 
> 
> 这个放开试试，不过要先自己编译pse文件夹里面的东西

感谢
