### ISSUE TITLE
CRNN根本跑不通

### ISSUE THREAD

**Issue by tangsipeng** [WenmuZhou/PytorchOCR#247]
麻烦检查并更新一下CRNN的训练吧

**Comment by ltm920716** [comment]
@tangsipeng 
按照这个先修改一下，可以训练
https://github.com/WenmuZhou/PytorchOCR/pull/246

**Comment by huangxin168** [comment]
> @tangsipeng 按照这个先修改一下，可以训练 #246

改了也不行，训练中文根本不收敛，话说你们自己跑过了吗？

**Comment by huangxin168** [comment]
可以训练，难收敛，看运气
