### ISSUE TITLE
为何训练时精度高，对训练集推理就全错？

### ISSUE THREAD

**Issue by Tomhardy13** [WenmuZhou/PytorchOCR#249]
训练时精度时1，并且验证集部分通过INFO，可以得知字符预测是正确的，但是重新推理结果没对过(推理的数据仍然是训练集和验证集中的)...有人碰到这种问题吗？

**Comment by LYHTZHANGJIANG** [comment]
你的问题有解决吗？我也遇到了  训练的acc 可以达到1 但是验证只有0.3  训练 和验证是一样的数据集。 测试也测试不到
