### ISSUE TITLE
【数据合成代码收集】

### ISSUE THREAD

**Issue by novioleo** [WenmuZhou/PytorchOCR#26]
https://github.com/airob0t/idcardgenerator
用于合成身份证图像

**Comment by novioleo** [comment]
https://github.com/tzattack/Idcard_random_generator
参考了airob0t的代码的身份证合成

**Comment by deep-practice** [comment]
https://github.com/deep-practice/fake_certificate_generator

**Comment by novioleo** [comment]
免费下载字体的网站【持续更新】

- http://www.zitiweb.com/

**Comment by Arctanxy** [comment]
> 免费下载字体的网站【持续更新】
> 
> * http://www.zitiweb.com/
> * http://www.diyiziti.com/

http://www.fonts.net.cn/fonts-zh-1.html  这个字体网站可以

**Comment by June-Li** [comment]
请问一下，DB、CRNN通用模型是用哪些数据集训练的呢？多谢多谢！！！
