### ISSUE TITLE
您好，作者，请问可以加载paddle的检测模型进行微调训练吗？

### ISSUE THREAD

**Issue by luoyq6** [WenmuZhou/PytorchOCR#265]

**Comment by novioleo** [comment]
可以

**Comment by luoyq6** [comment]
> 可以

用哪个配置文件呢？
![image](https://github.com/WenmuZhou/PytorchOCR/assets/110521846/f4b77704-cbb2-45f8-8b31-eb32476035d1)

**Comment by luoyq6** [comment]
@novioleo

**Comment by WenmuZhou** [comment]
使用dev分支，有我转换好的paddle模型
