### ISSUE TITLE
请问目前转换成onnx格式推理的功能可以使用了吗

### ISSUE THREAD

**Issue by Arlen-yuzu** [WenmuZhou/PytorchOCR#272]
模型从pth格式权重文件转为onnx格式后，推理结果变得不可用，在pth格式推理时还能正确预测，到了onnx格式虽然代码没有运行bug，但是输出得结果完全不可用，

**Comment by Arlen-yuzu** [comment]
ch_PP-OCRv4_rec这个模型在转onnx后使用会出现识别问题

**Comment by WenmuZhou** [comment]
可以了，你转换的时候加载权重了吗

**Comment by Arlen-yuzu** [comment]
可以检测了，可能是之前转换的过程有点问题，ch_PP-OCRv4_rec我重新转了一遍，现在是能够正常检测的
