### ISSUE TITLE
ch_ppocr_mobile_v2.0_cls_train 的 config文件是不是没上传？

### ISSUE THREAD

**Issue by GuangtaoLyu** [WenmuZhou/PytorchOCR#277]

**Comment by WenmuZhou** [comment]
我看网盘里有的
![image](https://github.com/WenmuZhou/PytorchOCR/assets/12406017/a839bcfe-320e-4254-a160-a36c8e328142)

**Comment by GuangtaoLyu** [comment]
> 我看网盘里有的 ![image](https://user-images.githubusercontent.com/12406017/271262220-a839bcfe-320e-4254-a160-a36c8e328142.png)

里面好像只有cls_v2.0 的 权重啊。 仓库里也没看到config 文件。

**Comment by WenmuZhou** [comment]
https://github.com/WenmuZhou/PytorchOCR/blob/dev/configs/cls/cls_mv3.yml  这不是吗
