### ISSUE TITLE
cls_mv3 模型权重是不是忘了上传了？ 链接里没有

### ISSUE THREAD

**Issue by GuangtaoLyu** [WenmuZhou/PytorchOCR#278]

**Comment by WenmuZhou** [comment]
我这边是有的哦
![image](https://github.com/WenmuZhou/PytorchOCR/assets/12406017/1b0fc781-4008-4777-aaf8-d930f89288d3)

**Comment by GuangtaoLyu** [comment]
> 我这边是有的哦 ![image](https://user-images.githubusercontent.com/12406017/271262051-1b0fc781-4008-4777-aaf8-d930f89288d3.png)

抱歉，我看这个名字是v2。  原来这个就是cls_mv3。
