### ISSUE TITLE
为什么新样本首次推理速度都会慢？

### ISSUE THREAD

**Issue by DemonDamon** [WenmuZhou/PytorchOCR#279]
![image](https://github.com/WenmuZhou/PytorchOCR/assets/20499644/ff39df16-cc3b-4fa2-a401-cd410a28528b)
如上图，我开了gpu，第一次推理很慢，同一个实例第二次推理非常快，什么原理请问？

关掉服务重启也一样。

尝试新的实例都一样，第一次都会很慢，第二次就很快，为什么呢？

**Comment by WenmuZhou** [comment]
第一次模型预热

**Comment by DemonDamon** [comment]
比如我第一次输了样本a需要5秒，第二次0.95秒，然后继续输入样本b也需要5秒？这事没太理解，那以后给用户使用，推理前我都得先后台跑一次？

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WenmuZhou** [comment]
第一次5s，后续的都是0.95s，也就是说加载模型后的第一次运行会慢，其他都ok

**Comment by DemonDamon** [comment]
不是的，换一个新样本进行推理，第一次还是5s？重复predict才变到0.95？

**Comment by ponykid** [comment]
请问问题解决了吗？我也遇见了这样的情况？

**Comment by ponykid** [comment]
https://blog.csdn.net/qq_40231159/article/details/120901785 这里给出了模型介绍
