### ISSUE TITLE
训练好的paddle模型，迁移到torch，又转onnx，进行推理为什么都识别不出来东西

### ISSUE THREAD

**Issue by Ivansyf34** [WenmuZhou/PytorchOCR#283]
![image](https://github.com/WenmuZhou/PytorchOCR/assets/93926232/555962c4-e3b1-4529-aaa8-538c9c40c320)
识别模型：configs\det\ch_PP-OCRv3\ch_PP-OCRv3_det_student.yml，迁移的res也很小，这是什么原因啊

**Comment by WenmuZhou** [comment]
先torch推理呢
