### ISSUE TITLE
大佬你好 ，想问个关于模型大小的问题

### ISSUE THREAD

**Issue by chenhengwang** [WenmuZhou/PytorchOCR#284]
我用的参数是ch_PP-OCRv4_det_student.yml里面的，没啥改动，然后训练出的模型大小是40m，我看到你给的best_accuracy.pth大小是12m左右，而且用你的模型推理速度也更快，想请问一下这个模型是怎样训练出来的呢，对于默认的参数有哪些改动吗？
十分感谢哈

**Comment by WenmuZhou** [comment]
训练出来的ckpt包含了优化器参数，需要提取才能得到模型参数
