### ISSUE TITLE
转trt

### ISSUE THREAD

**Issue by txy00001** [WenmuZhou/PytorchOCR#285]
你好，你的工作非常好，我最近也在做这个方面的工作，想问一下，1.你尝试过用paddle的ocr模型转trt吗？2.这个库里转出的onnx可以直接用trtexec 转成trt么？作者有测试过么？3.中文的ocr模型和英文的ocr模型有什么差异么？我调整后训练出来rec模型对于+，-,:这种符号不是很敏感，有什么优化或者模型选择的方式么？期待你的回复

**Comment by WenmuZhou** [comment]
1. 没有
2. 没有
3. 数据差异
4. 加数据
