### ISSUE TITLE
训练报错，求救大佬

### ISSUE THREAD

**Issue by ggsimida-cw** [WenmuZhou/PytorchOCR#290]
数据格式是这样的
![image](https://github.com/WenmuZhou/PytorchOCR/assets/83968749/b9965529-06ae-4806-b968-151904dc3fb1)
![image](https://github.com/WenmuZhou/PytorchOCR/assets/83968749/0bc6e36d-b648-4184-b3a6-c24745d190fd)
为啥会报错
![image](https://github.com/WenmuZhou/PytorchOCR/assets/83968749/2eccd0d5-4fa3-405e-a8a9-56c2e3b3c3d3)

**Comment by WenmuZhou** [comment]
训练数据集没有初始化
