### ISSUE TITLE
ch_PP-OCRv4_det_cml模块对齐精度不达标

### ISSUE THREAD

**Issue by guanfuchen** [WenmuZhou/PytorchOCR#294]
用这个convert_params_compute_diff.py脚本跑ch_PP-OCRv4_det_cml的结果精度差别大

save convert torch params to initmodels/ch_PP-OCRv4_det_train/best_accuracy.pth
paddle version: 2.6.1
input shape of paddle is (1, 3, 640, 640)
torch version: 2.0.1+cu117
input shape of torch is (1, 3, 640, 640)
Student_res 0.5748608
Student2_res 0.6177637
Teacher_res 0.68103516

**Comment by WenmuZhou** [comment]
paddle和torch都是这个配置吗https://github.com/WenmuZhou/PytorchOCR/blob/dev/configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_cml.yml
