### ISSUE TITLE
Can you provide the mbv3 config file?

### ISSUE THREAD

**Issue by deep-practice** [WenmuZhou/PytorchOCR#62]

**Comment by novioleo** [comment]
@deep-practice 
default config is: large,0.5
which config you need? can you point out?

**Comment by deep-practice** [comment]
det_train_db_config.py
 'backbone': {"type": "ResNet", 'layers': 18, 'pretrained': True}, # ResNet or MobileNetV3
Just change type to MobileNetV3?

**Comment by novioleo** [comment]
@deep-practice yeah.you can also specifiy 'scale','model_name' in config dict.
