### ISSUE TITLE
讯飞数据集使用DBNet loss不动

### ISSUE THREAD

**Issue by lovelyzzc** [WenmuZhou/PytorchOCR#74]
我使用讯飞的数据集训练，用了作者的数据转换脚本，
下载使用的resnet50预训练模型，
模型其他的配置都没有改，
在训练的时候，发现loss从头到尾都是1.000, loss_shrink和loss_threshold一直是0.
我想问一下这种情况是怎么回事。

在预测的时候我我用了很多张图片发现每张图都没有点，预测出来的全为空。
希望大佬能指点一下，谢谢谢谢！

**Comment by lovelyzzc** [comment]
我前面的问题都已经解决了

loss：在datasets/DetDataSet.py 72行
这一行针对讯飞的数据存在bug
讯飞的数据没有text，所以每一个gt都被跳过了，导致最后训练部分loss为0

其次在datasets/det_modules/random_crop_data.py 57行附近
data['text_polys'] = np.float32(text_polys_crop)
会出现错误
这个错误是因为原本的这一部分针对的是EAST模型的数据来做的，在EAST模型中始终使用4个点来做标记，但是在讯飞的数据里面，点是自适应的，存在大于4个点的情况，直接使用np.float32()就会存在错误,

在这里我的改法是在前面5行
text_polys_crop.append(poly)处，改为
text_polys_crop.append(np.float32(poly))

data['text_polys'] = np.float32(text_polys_crop) 处改为
data['text_polys'] = np.array(text_polys_crop)

至于第二个问题是因为我模型并没有训练好
很感谢作者提供的模型，让我对论文能够理解更深，
谢谢谢谢

**Comment by novioleo** [comment]
glad to hear that. @lovelyzzc
