### ISSUE TITLE
Chinese dataset training and demo support?

### ISSUE THREAD

**Issue by lucasjinreal** [WenmuZhou/PytorchOCR#84]
Does there any training support on both Chinese charactors detection and recognition?

**Comment by novioleo** [comment]
what's  your problem? ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JinTian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月27日(星期一) 下午5:55
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WenmuZhou/PytorchOCR] Chinese dataset training and demo support? (#84)

**Comment by jinfagang** [comment]
@novioleo  ??

**Comment by novioleo** [comment]
what problem you meet,can you provide it? the demos are exist in the tool directory.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;JinTian&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月27日(星期一) 晚上10:07
收件人:&nbsp;&quot;WenmuZhou/PytorchOCR&quot;<PytorchOCR@noreply.github.com&gt;;
抄送:&nbsp;&quot;Tao Luo&quot;<744351893@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [WenmuZhou/PytorchOCR] Chinese dataset training and demo support? (#84)
