### ISSUE TITLE
参数初始化?

### ISSUE THREAD

**Issue by Ykid** [WenmuZhou/PytorchOCR#89]
请问为何采用预设的参数初始化而不用其他的? 例如He initialization

**Comment by novioleo** [comment]
@Ykid 你可以在weight init里面定义自己的init函数~

**Comment by novioleo** [comment]
至于用不用hekaiming的那个，纯粹是因为目前的初始化函数用习惯了。不想改。

**Comment by Ykid** [comment]
感谢！
