### ISSUE TITLE
预测的时候报错

### ISSUE THREAD

**Issue by yangfei963158659** [WenmuZhou/PytorchOCR#91]
我用楼主提供的预训练的模型调用det_infer做预测的时候，会报错，提示 如下错误:

KeyError:'cfg',
是不是预训练的模型里面没有cfg

**Comment by WenmuZhou** [comment]
重新下载一下模型，最近更新了

**Comment by wayneszq** [comment]
hi, 尝试了db_ResNet50_vd_icdar2015.pth，还是有这个报错。修改日期是2020年8月8日。

**Comment by WenmuZhou** [comment]
刚刚看了一下，是因为这次传的模型我只存了模型参数，后面看情况更新一下

**Comment by GokulNC** [comment]
谢谢！

**Comment by alex152738** [comment]
> 谢谢！

请问这个问题解决了吗，我也遇到了同样的问题。

**Comment by GokulNC** [comment]
使用最新的 `db_ResNet50_vd_icdar2015withconfig.pth` 和 `db_mbv3_icdar2015withconfig.pth`

**Comment by alex152738** [comment]
> 使用最新的 `db_ResNet50_vd_icdar2015withconfig.pth` 和 `db_mbv3_icdar2015withconfig.pth`
谢谢！

**Comment by novioleo** [comment]
应该没有问题了，如有问题，重新打开~
