### ISSUE TITLE
error occure when start evaluate   -rec_train.py

### ISSUE THREAD

**Issue by JF-Lee** [WenmuZhou/PytorchOCR#99]
![image](https://user-images.githubusercontent.com/66176517/94369413-210acc80-011c-11eb-83b4-2a5a5af888d6.png)

**Comment by ouyang25** [comment]
你数据集的格式不对啊

**Comment by novioleo** [comment]
大概率不会吧。你可以排查下报错的时候的那个all_same_height_images是不是len 是不是0.

**Comment by w452144816** [comment]
config.dataset 的 'loader' 字段 'type': 'DataLoader',  train和eval 在配置文件中不一致， 都改成 'type': 'DataLoader', 就好了
